import { IMPORT_ENTITIES, type ImportCapability, type ImportEntity } from "./types";

export type EntityPack = {
  key: ImportEntity;
  label: string;
  group: "crm" | "ams" | "desk";
  hint: string;
  match: string;
  capability: ImportCapability;
  coming?: string;
  jsonExport?: boolean;
  headers: readonly string[];
};

export const ENTITY_PACKS: EntityPack[] = [
  {
    key: "leads",
    label: "Leads",
    group: "crm",
    hint: "Inbound people before a Contact exists. Match on email.",
    match: "email",
    capability: "full",
    headers: [
      "id",
      "external_key",
      "first_name",
      "last_name",
      "email",
      "phone",
      "source",
      "status",
      "notes",
      "mailing_address",
      "city",
      "state",
      "zip",
      "date_of_birth",
      "insurance_type_desired",
      "preferred_language",
      "owner_email",
    ],
  },
  {
    key: "contacts",
    label: "Contacts",
    group: "crm",
    hint: "People records — not businesses. Match on email.",
    match: "email",
    capability: "full",
    headers: [
      "id",
      "external_key",
      "first_name",
      "last_name",
      "email",
      "phone",
      "mailing_address",
      "city",
      "state",
      "zip",
      "date_of_birth",
      "language",
      "marital_status",
      "source",
      "notes",
      "client_status",
      "status",
      "owner_email",
    ],
  },
  {
    key: "businesses",
    label: "Accounts",
    group: "crm",
    hint: "Commercial accounts — not Contacts. Match on email, then name.",
    match: "email or name",
    capability: "full",
    headers: [
      "id",
      "external_key",
      "name",
      "legal_name",
      "dba",
      "email",
      "phone",
      "mailing_address",
      "city",
      "state",
      "zip",
      "entity_type",
      "naics",
      "website",
      "notes",
      "ein_last4",
    ],
  },
  {
    key: "deals",
    label: "Deals / Opportunities",
    group: "crm",
    hint: "Shopping pipeline. Match on id, then title + contact email.",
    match: "id or title + contact_email",
    capability: "full",
    headers: [
      "id",
      "external_key",
      "title",
      "pipeline_stage",
      "line_of_business",
      "state",
      "notes",
      "source",
      "contact_email",
      "account_name",
      "lead_email",
      "account_kind",
      "bind_target",
      "coverage_amount",
      "current_carrier",
      "owner_email",
    ],
  },
  {
    key: "policies",
    label: "Policies",
    group: "ams",
    hint: "In-force book. Match on policy number. Never deletes.",
    match: "policy_number",
    capability: "full",
    headers: [
      "id",
      "external_key",
      "policy_number",
      "line_of_business",
      "status",
      "premium",
      "effective_date",
      "expiration_date",
      "contact_email",
      "account_name",
      "carrier_code",
      "carrier_name",
      "producer",
      "coverage_a",
      "form_type",
      "owner_email",
    ],
  },
  {
    key: "carriers",
    label: "Carriers / Markets",
    group: "ams",
    hint: "Markets and written lines. Match on agency code, then NAIC, then name.",
    match: "agency_code or naic or name",
    capability: "full",
    headers: [
      "id",
      "name",
      "naic",
      "agency_code",
      "written_lines",
      "portal_url",
      "website",
      "am_best_rating",
      "territory",
      "binding_authority",
      "appetite_notes",
      "active",
    ],
  },
  {
    key: "activities",
    label: "Activities",
    group: "desk",
    hint: "Tasks, meetings, and calls. Export is live. Import creates new rows only.",
    match: "id",
    capability: "stub",
    headers: [
      "id",
      "kind",
      "title",
      "notes",
      "status",
      "due_at",
      "start_at",
      "end_at",
      "assignee",
      "contact_email",
      "account_name",
      "deal_title",
      "policy_number",
      "lead_email",
      "phone_number",
      "direction",
      "meeting_type",
      "outcome",
    ],
  },
  {
    key: "notes",
    label: "Notes",
    group: "desk",
    hint: "Activity log bodies and client history. Import creates history rows only.",
    match: "id",
    capability: "stub",
    headers: [
      "id",
      "source",
      "body",
      "event_type",
      "occurred_at",
      "contact_email",
      "account_name",
      "deal_title",
      "policy_number",
      "lead_email",
    ],
  },
  {
    key: "documents",
    label: "Documents",
    group: "desk",
    hint: "Attachment list — filename and metadata. File zip export is later.",
    match: "filename",
    capability: "export_only",
    coming: "Binary zip export later. CSV of the attachment list is live.",
    headers: [
      "id",
      "filename",
      "mime_type",
      "doc_type",
      "slot",
      "status",
      "library",
      "contact_email",
      "account_name",
      "deal_title",
      "policy_number",
      "created_at",
    ],
  },
  {
    key: "commissions",
    label: "Commissions",
    group: "ams",
    hint: "Producer pay. Import is Admin-only and never deletes a statement.",
    match: "id or policy_number + period",
    capability: "careful",
    headers: [
      "id",
      "policy_number",
      "carrier_name",
      "line_of_business",
      "premium",
      "rate_pct",
      "amount",
      "status",
      "due_date",
      "paid_date",
      "period",
      "agent_email",
    ],
  },
  {
    key: "quotes",
    label: "Quote Sheets / Quotes",
    group: "ams",
    hint: "Quote rows plus Quote Sheet JSON. Import does not overwrite confirmed sheet values.",
    match: "quote_number",
    capability: "export_only",
    jsonExport: true,
    coming: "Import stays off so confirmed Quote Sheet values cannot be overwritten.",
    headers: [
      "id",
      "deal_id",
      "deal_title",
      "carrier_name",
      "quote_number",
      "premium",
      "coverage_a",
      "bindable",
      "lost_reason",
      "notes",
      "created_at",
    ],
  },
  {
    key: "users",
    label: "Users / Agents",
    group: "desk",
    hint: "Roster export. Import creates an invite stub — it does not set a password.",
    match: "email",
    capability: "stub",
    headers: [
      "id",
      "name",
      "email",
      "username",
      "role",
      "access_status",
      "office_label",
      "territory_label",
      "active",
    ],
  },
  {
    key: "pipelines",
    label: "Pipelines / Stages",
    group: "desk",
    hint: "Config picklists. Stages always carry pipeline_id or pipeline_slug.",
    match: "pipeline_slug + stage_slug",
    capability: "full",
    headers: [
      "pipeline_id",
      "pipeline_slug",
      "pipeline_name",
      "pipeline_kind",
      "pipeline_sort",
      "stage_id",
      "stage_slug",
      "stage_name",
      "stage_sort",
    ],
  },
  {
    key: "appetite",
    label: "Appetite rules",
    group: "ams",
    hint: "Carrier appetite floors. Export only — live rater dumps stay out.",
    match: "carrier_code + line",
    capability: "export_only",
    coming: "Import of appetite rules is not offered. Edit rules on Carriers.",
    headers: [
      "id",
      "carrier_name",
      "carrier_code",
      "line_of_business",
      "min_cov_a",
      "max_cov_a",
      "max_roof_age",
      "coastal_allowed",
      "mobile_allowed",
      "notes",
    ],
  },
  {
    key: "declines",
    label: "Decline / attempt logs",
    group: "ams",
    hint: "Quote attempt history. Export only.",
    match: "id",
    capability: "export_only",
    coming: "Logs are append-only from shops. Import is not offered.",
    headers: [
      "id",
      "deal_title",
      "carrier_name",
      "result",
      "bindable",
      "quote_number",
      "premium",
      "cov_a_tried",
      "why",
      "lost_reason",
      "attempted_at",
    ],
  },
];

export function packFor(entity: string): EntityPack | null {
  return ENTITY_PACKS.find((pack) => pack.key === entity) ?? null;
}

export function isImportEntity(value: string): value is ImportEntity {
  return (IMPORT_ENTITIES as readonly string[]).includes(value);
}

export function canImport(pack: EntityPack): boolean {
  return pack.capability === "full" || pack.capability === "careful" || pack.capability === "stub";
}

export function templateCsv(headers: readonly string[]): string {
  return `${headers.join(",")}\r\n`;
}
