import { existsSync, readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

function source(file: string) {
  return readFileSync(file, "utf8");
}

describe("Renewals desk chrome", () => {
  it("uses an urgency-only board, pulse, and corner Today Activity on /renewals", () => {
    const desk = source("src/components/renewals/renewals-desk.tsx");
    const views = source("src/components/renewals/renewals-filtered-views.tsx");
    const board = source("src/components/renewals/renewals-urgency-board.tsx");
    const urgency = source("src/lib/renewal/urgency.ts");
    const card = source("src/components/renewals/renewal-card.tsx");
    const pulse = source("src/components/renewals/renewals-pulse.tsx");
    const corner = source("src/components/desk/today-activity-corner.tsx");
    const renewalsPage = source("src/app/renewals/page.tsx");
    const dealsPage = source("src/app/deals/page.tsx");

    expect(desk).toMatch(/DealWorkspaceBar/);
    expect(desk).toMatch(/TodayActivityCorner/);
    expect(desk).toMatch(/DealWorkQueuePanel/);
    expect(desk).toMatch(/PipelineBookModeToggle/);
    expect(desk).toMatch(/pipelineBookToggleHrefs\(view, "renewals"\)/);
    expect(desk).toMatch(/cookieKey=\{RENEWALS_VIEW_COOKIE\}/);
    expect(desk).toMatch(/hrefBuilder=\{renewalsHref\}/);
    expect(desk).toMatch(/boardWhenNoPipeline=\{null\}/);
    expect(desk).toMatch(/basePath="\/renewals"/);
    expect(desk).toMatch(/PipelineFilterPopover/);
    expect(desk).toMatch(/renewals-pipeline/);
    expect(desk).toMatch(/RenewalsFilteredViews/);
    expect(desk).toMatch(/RenewalsPulse/);
    expect(desk).toMatch(/data-ff-renewals-glance/);
    expect(desk).not.toMatch(/DeskTruthStrip/);
    expect(desk).not.toMatch(/renewalHeatShares/);
    expect(desk).not.toMatch(/RenewalsList/);
    expect(desk).not.toMatch(/TodayActivityStrip/);
    expect(desk).not.toMatch(/deal-upload-activity/);
    expect(desk).not.toMatch(/deal-today-slot/);
    expect(views).toMatch(/RenewalsUrgencyBoard/);
    expect(views).toMatch(/RenewalsPriorityStack/);
    expect(views).toMatch(/RenewalsHostList/);
    expect(views).not.toMatch(/RenewalsKanban/);
    expect(views).not.toMatch(/RenewalsTable/);
    expect(views).not.toMatch(/RenewalsFunnel/);
    expect(views).not.toMatch(/RenewalsList/);
    expect(views).not.toMatch(/RenewalsWorkspace/);
    expect(source("src/components/deals/deal-workspace-bar.tsx")).toMatch(/\["board", "Board"\]/);
    expect(source("src/components/deals/deal-workspace-bar.tsx")).toMatch(/\["stack", "Stack"\]/);
    expect(source("src/components/deals/deal-workspace-bar.tsx")).toMatch(/\["list", "List"\]/);
    expect(source("src/components/deals/deal-workspace-bar.tsx")).not.toMatch(/\["grid", "Grid"\]/);
    expect(source("src/components/deals/deal-workspace-bar.tsx")).not.toMatch(/\["funnel", "Funnel"\]/);
    expect(source("src/components/renewals/renewals-priority-stack.tsx")).toMatch(
      /data-ff-renewals-priority-stack/,
    );
    expect(source("src/components/renewals/renewals-priority-stack.tsx")).toMatch(/ff-stack-card/);
    expect(source("src/components/renewals/renewals-priority-stack.tsx")).toMatch(/ff-stack-glyph/);
    expect(source("src/components/renewals/renewals-priority-stack.tsx")).toMatch(/renewalStackHeat/);
    expect(source("src/components/renewals/renewals-priority-stack.tsx")).toMatch(/Work renewal/);
    expect(source("src/components/renewals/renewals-priority-stack.tsx")).toMatch(/\/compare/);
    expect(source("src/components/renewals/renewals-priority-stack.tsx")).toMatch(/data-ff-compare-eye|RenewalCompareDrawer/);
    expect(source("src/components/renewals/renewals-priority-stack.tsx")).toMatch(/renewalRiskHover/);
    expect(source("src/components/renewals/renewals-priority-stack.tsx")).not.toMatch(/ff-stack-action/);
    expect(source("src/components/renewals/renewals-host-list.tsx")).toMatch(/data-ff-renewals-host-list/);
    expect(board).toMatch(/RENEWAL_URGENCY_BANDS/);
    expect(board).toMatch(/data-ff-urgency-band/);
    expect(board).not.toMatch(/Upcoming|Contacted|Quoted|Bound|Lost/);
    expect(urgency).toMatch(/Under 30 days/);
    expect(urgency).toMatch(/30–60 days/);
    expect(urgency).toMatch(/60–90 days/);
    expect(urgency).toMatch(/90\+ days/);
    expect(urgency).not.toMatch(/Upcoming|Contacted|Quoted|Bound|Lost/);
    expect(card).toMatch(/clientName/);
    expect(card).toMatch(/data-ff-risk-badge/);
    expect(card).toMatch(/premiumDelta/);
    expect(card).toMatch(/renewalWhyLine/);
    expect(card).toMatch(/RenewalCompareDrawer/);
    expect(card).toMatch(/RenewalHealthMeter/);
    expect(card).toMatch(/renewalPolicyTypeLabel/);
    expect(card).toMatch(/data-ff-health-info/);
    expect(card).not.toMatch(/>\s*Policy\s*</);
    expect(card).toMatch(/sendRenewalChase/);
    expect(card).toMatch(/RenewalMiniReview/);
    expect(pulse).toMatch(/data-ff-renewals-pulse/);
    expect(pulse).toMatch(/data-ff-pulse-depth/);
    expect(pulse).toMatch(/Book pulse/);
    expect(pulse).toMatch(/--ff-heat-hot/);
    expect(desk).toMatch(/ff-renewals-glance/);
    expect(desk).toMatch(/roleHealthSummary/);
    expect(card).toMatch(/autopilotConfirmLabel|data-ff-autopilot/);
    expect(card).toMatch(/data-ff-autopilot-badge/);
    expect(source("src/lib/renewal/autopilot.ts")).toMatch(/AUTOPILOT_SILENCE_DAYS/);
    expect(source("src/lib/notifications/panel.ts")).toMatch(/renewal_autopilot/);
    expect(source("src/lib/renewal/health-rollup.ts")).toMatch(/Never per-policy primary/);
    expect(source("src/components/renewals/renewal-compare-drawer.tsx")).toMatch(/data-ff-compare-eye/);
    expect(source("src/components/renewals/renewal-compare-drawer.tsx")).toMatch(/ff-renewal-compare-dark/);
    expect(source("src/lib/renewal/gemini-diff.ts")).toMatch(/bothSides/);
    expect(source("src/lib/renewal/gemini-diff.ts")).toMatch(/snapshot only|fallback/);
    expect(corner).toMatch(/data-ff-today-activity-corner/);
    expect(corner).toMatch(/Open Today Activity/);
    expect(corner).toMatch(/Collapse Today Activity/);
    expect(corner).toMatch(/TodayActivityStrip/);
    expect(desk).toMatch(/No archived renewals yet/);
    expect(desk).toMatch(/Classic queue/);
    expect(desk).toMatch(/Book health/);
    expect(renewalsPage).toMatch(/RenewalsDesk/);
    expect(renewalsPage).toMatch(/DeskPageTrail/);
    expect(renewalsPage).toMatch(/Back to policy/);
    expect(renewalsPage).toMatch(/canEditStages=\{session.isAdmin\}/);
    expect(dealsPage).toMatch(/book === "renewals"/);
    expect(dealsPage).toMatch(/<RenewalsDesk/);
    expect(dealsPage).not.toMatch(/RenewalsWorkspace/);
    expect(existsSync("src/components/renewals/renewals-list.tsx")).toBe(false);
    expect(existsSync("src/components/renewals/renewals-table.tsx")).toBe(false);
    expect(existsSync("src/components/renewals/renewals-funnel.tsx")).toBe(false);
    expect(existsSync("src/components/renewals/renewals-kanban.tsx")).toBe(false);
    expect(existsSync("src/components/renewals/renewals-workspace.tsx")).toBe(false);
  });

  it("keeps coverage-gap and cross-sell prompts off the urgency board, stack, and classic queue", () => {
    const board = source("src/components/renewals/renewals-urgency-board.tsx");
    const stack = source("src/components/renewals/renewals-priority-stack.tsx");
    const card = source("src/components/renewals/renewal-card.tsx");
    const queue = source("src/app/renewals/queue/page.tsx");
    const deskData = source("src/lib/renewal/board-data.ts");
    const desk = source("src/components/renewals/renewals-desk.tsx");
    expect(board).not.toMatch(/GapCountBadge/);
    expect(stack).not.toMatch(/GapCountBadge/);
    expect(card).not.toMatch(/GapCountBadge/);
    expect(queue).not.toMatch(/GapCountBadge/);
    expect(queue).not.toMatch(/loadRenewalGapCounts/);
    expect(card).not.toMatch(/RenewalCrossSellPanel/);
    expect(card).not.toMatch(/data-ff-renewal-cross-sell/);
    expect(desk).not.toMatch(/emailTemplates/);
    expect(deskData).not.toMatch(/gapCount/);
    expect(deskData).not.toMatch(/crossSell/);
    expect(deskData).not.toMatch(/analyzeCoverageGaps|householdGapCount|missingRenewalCrossSellLines/);
  });

  it("keeps RenewalGapStrip off policy renewal views and deal tabs", () => {
    const policy = source("src/app/policies/[id]/page.tsx");
    const deal = source("src/app/deals/[id]/page.tsx");
    expect(policy).not.toMatch(/RenewalGapStrip/);
    expect(policy).not.toMatch(/loadRenewalGapItems/);
    expect(policy).not.toMatch(/Add product to package/);
    expect(deal).not.toMatch(/RenewalGapStrip/);
    expect(deal).not.toMatch(/loadRenewalGapItems/);
    expect(deal).not.toMatch(/GapPanel/);
  });

  it("keeps deals and renewals default-view cookies independent", () => {
    const cookieNames = source("src/lib/wire/pipeline-view-cookies.ts");
    const prefs = source("src/app/actions/pipeline-view-prefs.ts");
    const bar = source("src/components/deals/deal-workspace-bar.tsx");
    expect(cookieNames).toMatch(/ff_pipeline_view/);
    expect(cookieNames).toMatch(/ff_renewals_view/);
    expect(prefs).toMatch(/pipeline-view-cookies/);
    expect(bar).toMatch(/hrefBuilder/);
    expect(bar).toMatch(/RENEWALS_VIEW_COOKIE/);
    expect(source("src/lib/wire/pipeline.ts")).toMatch(/export function renewalsHref/);
    expect(source("src/lib/wire/pipeline.ts")).toMatch(/parseRenewalsView/);
  });
});
