import { computePolicyCommission } from "../commissions/policy-math";
import { lineOfBusinessFromZoho } from "../commissions/zoho-fields";
import {
  ADMIN_USER_ID,
  TENANT_ID,
  ZOHO_COMMISSION_IDS,
  ZOHO_CONTACT_IDS,
  ZOHO_POLICY_IDS,
} from "../fixtures/ids";
import { db } from "./index";
import { commissions, contacts, policies } from "./schema";

/**
 * Live Zoho Policies copies. Field values are from the live org.
 * Local desk only — no Zoho writes. Ana Dib is not in this set.
 */
const COPIES = [
  {
    contactId: ZOHO_CONTACT_IDS.ochoa,
    firstName: "Jonathan",
    lastName: "Ochoa",
    city: "Melbourne",
    policyId: ZOHO_POLICY_IDS.ochoaLife,
    commissionId: ZOHO_COMMISSION_IDS.ochoaLife,
    policyNumber: "359207-97",
    insuranceType: "Life",
    policyType: "Life",
    policySubType: "Accidental Death",
    sellingAgency: "backnine",
    gwp: 620.4,
    commission4: 80,
    premiumFrequency: "Annual",
    numberOfInsured: null as number | null,
    paymentStatus: "Paid",
    status: "paid" as const,
    effective: "2024-07-09T16:00:00.000Z",
    expiration: "2025-07-09T16:00:00.000Z",
    dueDate: "2024-08-08T16:00:00.000Z",
    paidDate: "2024-08-08T16:00:00.000Z",
    period: "2024-07",
    notes: "Live Zoho Life copy. Accidental Death / BackNine. Commission4 80.",
  },
  {
    contactId: ZOHO_CONTACT_IDS.cromartie,
    firstName: "Mario",
    lastName: "Cromartie",
    city: "Palm Bay",
    policyId: ZOHO_POLICY_IDS.cromartieDp3,
    commissionId: ZOHO_COMMISSION_IDS.cromartieDp3,
    policyNumber: "PFL677036-00",
    insuranceType: "P&C",
    policyType: "Renter & Landord",
    policySubType: "DP3",
    sellingAgency: "afa",
    gwp: 3158,
    commission4: 10,
    premiumFrequency: "Annual",
    numberOfInsured: null,
    paymentStatus: "Outstanding",
    status: "pending" as const,
    effective: "2026-09-10T16:00:00.000Z",
    expiration: "2027-09-10T16:00:00.000Z",
    dueDate: "2026-10-10T16:00:00.000Z",
    paidDate: null as string | null,
    period: "2026-09",
    notes: "Live Zoho P&C AFA copy. DP3 Commission4 10 → TAC at 5%.",
  },
  {
    contactId: ZOHO_CONTACT_IDS.palacios,
    firstName: "Virginia",
    lastName: "Palacios",
    city: "Orlando",
    policyId: ZOHO_POLICY_IDS.palaciosWc,
    commissionId: ZOHO_COMMISSION_IDS.palaciosWc,
    policyNumber: "WC PC 924909-000",
    insuranceType: "P&C",
    policyType: "Commercial",
    policySubType: "Workers' Comp",
    sellingAgency: "first_connect",
    gwp: 14200,
    commission4: 10,
    premiumFrequency: "Monthly",
    numberOfInsured: null,
    paymentStatus: "Monthly",
    status: "payable" as const,
    effective: "2026-05-05T16:00:00.000Z",
    expiration: "2027-05-05T16:00:00.000Z",
    dueDate: "2026-06-05T16:00:00.000Z",
    paidDate: null,
    period: "2026-05",
    notes: "Live Zoho First Connect WC. Monthly = TAC/12.",
  },
  {
    contactId: ZOHO_CONTACT_IDS.palacios,
    firstName: "Virginia",
    lastName: "Palacios",
    city: "Orlando",
    policyId: ZOHO_POLICY_IDS.palaciosGl,
    commissionId: ZOHO_COMMISSION_IDS.palaciosGl,
    policyNumber: "CEG-00469480-00",
    insuranceType: "P&C",
    policyType: "Commercial",
    policySubType: "General Liability",
    sellingAgency: "first_connect",
    gwp: 4038,
    commission4: 10,
    premiumFrequency: "Annual",
    numberOfInsured: null,
    paymentStatus: "Paid",
    status: "paid" as const,
    effective: "2026-05-05T16:00:00.000Z",
    expiration: "2027-05-05T16:00:00.000Z",
    dueDate: "2026-06-05T16:00:00.000Z",
    paidDate: "2026-06-01T16:00:00.000Z",
    period: "2026-05",
    notes: "Live Zoho First Connect GL. Annual frequency → Monthly 0.",
  },
  {
    contactId: ZOHO_CONTACT_IDS.logan,
    firstName: "Natasha",
    lastName: "Logan",
    city: "Titusville",
    policyId: ZOHO_POLICY_IDS.loganGl,
    commissionId: ZOHO_COMMISSION_IDS.loganGl,
    policyNumber: "CSG-00544929-00",
    insuranceType: "P&C",
    policyType: "Commercial",
    policySubType: "General Liability",
    sellingAgency: "agentero",
    gwp: 359,
    commission4: 14,
    premiumFrequency: "Annual",
    numberOfInsured: null,
    paymentStatus: "Outstanding",
    status: "pending" as const,
    effective: "2026-08-29T16:00:00.000Z",
    expiration: "2027-08-29T16:00:00.000Z",
    dueDate: "2026-09-28T16:00:00.000Z",
    paidDate: null,
    period: "2026-08",
    notes: "Live Zoho Agentero GL. Full Commission4 14%, not halved.",
  },
  {
    contactId: ZOHO_CONTACT_IDS.mcalister,
    firstName: "Douglas",
    lastName: "Mcalister",
    city: "Cocoa",
    policyId: ZOHO_POLICY_IDS.mcalisterMkt,
    commissionId: ZOHO_COMMISSION_IDS.mcalisterMkt,
    policyNumber: "Marketplace",
    insuranceType: "Health",
    policyType: "Health",
    policySubType: "Marketplace",
    sellingAgency: "pimsco_agility",
    gwp: 30,
    commission4: null as number | null,
    premiumFrequency: "Monthly",
    numberOfInsured: 2,
    paymentStatus: "Monthly",
    status: "payable" as const,
    effective: "2026-01-01T16:00:00.000Z",
    expiration: "2026-12-31T16:00:00.000Z",
    dueDate: "2026-02-01T16:00:00.000Z",
    paidDate: null,
    period: "2026-01",
    notes: "Live Zoho Marketplace. GWP is PMPM $30 × 2 insured.",
  },
  {
    contactId: ZOHO_CONTACT_IDS.seraphin,
    firstName: "Fritzs",
    lastName: "Seraphin",
    city: "Melbourne",
    policyId: ZOHO_POLICY_IDS.seraphinMa,
    commissionId: ZOHO_COMMISSION_IDS.seraphinMa,
    policyNumber: "Medicare",
    insuranceType: "Health",
    policyType: "Health",
    policySubType: "Medicare Advantage",
    sellingAgency: "pimsco_agility",
    gwp: 363,
    commission4: null,
    premiumFrequency: "Annual",
    numberOfInsured: null,
    paymentStatus: "Paid",
    status: "paid" as const,
    effective: "2026-01-01T16:00:00.000Z",
    expiration: "2026-12-31T16:00:00.000Z",
    dueDate: "2026-01-15T16:00:00.000Z",
    paidDate: "2026-01-15T16:00:00.000Z",
    period: "2026-01",
    notes: "Live Zoho Medicare Advantage. One-time TAC = GWP $363.",
  },
  {
    contactId: ZOHO_CONTACT_IDS.valencia,
    firstName: "Amayrani",
    lastName: "Valencia",
    city: "Palm Bay",
    policyId: ZOHO_POLICY_IDS.valenciaSupp,
    commissionId: ZOHO_COMMISSION_IDS.valenciaSupp,
    policyNumber: "451188218",
    insuranceType: "Health",
    policyType: "Health",
    policySubType: "Supplemental Health",
    sellingAgency: "pimsco_agility",
    gwp: 115.49,
    commission4: 25,
    premiumFrequency: "Monthly",
    numberOfInsured: null,
    paymentStatus: "Monthly",
    status: "payable" as const,
    effective: "2026-06-13T16:00:00.000Z",
    expiration: "2027-06-13T16:00:00.000Z",
    dueDate: "2026-07-13T16:00:00.000Z",
    paidDate: null,
    period: "2026-06",
    notes: "Live Zoho Supplemental. Commission4 25. Monthly = GWP × %.",
  },
] as const;

export async function seedZohoPolicyCommissions() {
  const uniqueContacts = new Map<string, (typeof COPIES)[number]>();
  for (const row of COPIES) {
    if (!uniqueContacts.has(row.contactId)) uniqueContacts.set(row.contactId, row);
  }

  for (const row of uniqueContacts.values()) {
    const policyCount = COPIES.filter((copy) => copy.contactId === row.contactId).length;
    await db
      .insert(contacts)
      .values({
        id: row.contactId,
        tenantId: TENANT_ID,
        firstName: row.firstName,
        lastName: row.lastName,
        city: row.city,
        state: "FL",
        tenureStart: new Date(row.effective),
        policyCount,
        notes: `${row.notes} Not the Ana Dib shop.`,
        ownerId: ADMIN_USER_ID,
      })
      .onConflictDoUpdate({
        target: contacts.id,
        set: {
          firstName: row.firstName,
          lastName: row.lastName,
          city: row.city,
          policyCount,
          notes: `${row.notes} Not the Ana Dib shop.`,
          ownerId: ADMIN_USER_ID,
          updatedAt: new Date(),
        },
      });
  }

  for (const row of COPIES) {
    const computed = computePolicyCommission(row);
    const line = lineOfBusinessFromZoho(row.insuranceType, row.policyType, row.policySubType);
    const gwp = row.gwp.toFixed(2);
    const rate = row.commission4 == null ? "0.00" : row.commission4.toFixed(2);
    const tac = computed.totalAnnualCommission.toFixed(2);

    await db
      .insert(policies)
      .values({
        id: row.policyId,
        tenantId: TENANT_ID,
        contactId: row.contactId,
        policyNumber: row.policyNumber,
        lineOfBusiness: line,
        status: "active",
        effectiveDate: new Date(row.effective),
        expirationDate: new Date(row.expiration),
        premium: gwp,
        insuranceType: row.insuranceType,
        policyType: row.policyType,
        policySubType: row.policySubType,
        premiumFrequency: row.premiumFrequency,
        numberOfInsured: row.numberOfInsured,
        gwp,
        commission4: row.commission4 == null ? null : rate,
        ownerId: ADMIN_USER_ID,
      })
      .onConflictDoUpdate({
        target: policies.id,
        set: {
          contactId: row.contactId,
          policyNumber: row.policyNumber,
          lineOfBusiness: line,
          premium: gwp,
          insuranceType: row.insuranceType,
          policyType: row.policyType,
          policySubType: row.policySubType,
          premiumFrequency: row.premiumFrequency,
          numberOfInsured: row.numberOfInsured,
          gwp,
          commission4: row.commission4 == null ? null : rate,
          ownerId: ADMIN_USER_ID,
          updatedAt: new Date(),
        },
      });

    await db
      .insert(commissions)
      .values({
        id: row.commissionId,
        tenantId: TENANT_ID,
        agentId: ADMIN_USER_ID,
        policyId: row.policyId,
        lineOfBusiness: line,
        premium: gwp,
        ratePct: rate,
        amount: tac,
        agencyAmount: tac,
        producerAmount: tac,
        sellingAgency: row.sellingAgency,
        status: row.status,
        dueDate: row.dueDate ? new Date(row.dueDate) : null,
        paidDate: row.paidDate ? new Date(row.paidDate) : null,
        paidByUserId: row.status === "paid" ? ADMIN_USER_ID : null,
        period: row.period,
        insuranceType: row.insuranceType,
        policyType: row.policyType,
        policySubType: row.policySubType,
        premiumFrequency: row.premiumFrequency,
        numberOfInsured: row.numberOfInsured,
        gwp,
        commission4: row.commission4 == null ? null : rate,
        initialCommission: computed.initialCommission.toFixed(2),
        deferredCommission: computed.deferredCommission.toFixed(2),
        monthlyCommission: computed.monthlyCommission.toFixed(2),
        totalAnnualCommission: tac,
        paymentStatus: row.paymentStatus,
        paymentReferenceBatch: null,
      })
      .onConflictDoUpdate({
        target: commissions.id,
        set: {
          policyId: row.policyId,
          lineOfBusiness: line,
          premium: gwp,
          ratePct: rate,
          amount: tac,
          agencyAmount: tac,
          producerAmount: tac,
          sellingAgency: row.sellingAgency,
          status: row.status,
          dueDate: row.dueDate ? new Date(row.dueDate) : null,
          paidDate: row.paidDate ? new Date(row.paidDate) : null,
          paidByUserId: row.status === "paid" ? ADMIN_USER_ID : null,
          period: row.period,
          insuranceType: row.insuranceType,
          policyType: row.policyType,
          policySubType: row.policySubType,
          premiumFrequency: row.premiumFrequency,
          numberOfInsured: row.numberOfInsured,
          gwp,
          commission4: row.commission4 == null ? null : rate,
          initialCommission: computed.initialCommission.toFixed(2),
          deferredCommission: computed.deferredCommission.toFixed(2),
          monthlyCommission: computed.monthlyCommission.toFixed(2),
          totalAnnualCommission: tac,
          paymentStatus: row.paymentStatus,
          updatedAt: new Date(),
        },
      });
  }
}
