/** Maps dec / wind-mit / auto-dec labels onto Quote Sheet extract keys. */

export const EXTRACT_LABELS: Record<string, string> = {
  address: "Location",
  city: "City",
  county: "County",
  state: "State",
  zip: "ZIP",
  year_built: "Year built",
  construction: "Construction",
  occupancy: "Occupancy",
  stories: "Stories",
  square_feet: "Square feet",
  beds: "Bedrooms",
  baths: "Bathrooms",
  coverage_a: "Coverage A",
  coverage_b: "Coverage B",
  coverage_c: "Coverage C",
  coverage_d: "Coverage D",
  hurricane_deductible: "Hurricane deductible",
  aop_deductible: "AOP deductible",
  wind_deductible: "Wind deductible",
  roof_year: "Roof year",
  roof_covering: "Roof covering",
  roof_shape: "Roof shape",
  opening_protection: "Opening protection",
  pool: "Pool",
  protection_class: "Protection class",
  miles_to_coast: "Miles to coast",
  mobile_home: "Mobile home",
  replacement_cost_estimate: "Replacement cost (RCE)",
  current_carrier: "Current carrier",
  current_premium: "Current premium",
  effective_date: "Effective date",
  expiration_date: "Expiration date",
  policy_number: "Policy number",
  form: "Form",
  named_insured: "Named insured",
  mortgagee: "Mortgagee",
  flood_zone: "Flood zone",
  four_point_date: "4-point date",
  four_point_result: "4-point result",
  wind_mit_form: "Wind mit form",
  vin: "VIN",
  vehicle_year: "Vehicle year",
  vehicle_make: "Make",
  vehicle_model: "Model",
  vehicle_usage: "Usage",
  garaging_zip: "Garaging ZIP",
  garaging_address: "Garaging address",
  liability_bi: "BI limits",
  liability_pd: "PD limit",
  um_uim: "UM / UIM",
  pip: "PIP",
  comp_deductible: "Comp deductible",
  collision_deductible: "Collision deductible",
};

/** Lowercased, punctuation-stripped label → extract key. */
export const LABEL_ALIASES: Record<string, string> = {
  location: "address",
  propertyaddress: "address",
  insuredlocation: "address",
  propertylocation: "address",
  residencepremises: "address",
  city: "city",
  locationcity: "city",
  county: "county",
  state: "state",
  zip: "zip",
  zipcode: "zip",
  postalcode: "zip",
  yearbuilt: "year_built",
  yrblt: "year_built",
  yrbuilt: "year_built",
  built: "year_built",
  yearofconstruction: "year_built",
  construction: "construction",
  const: "construction",
  occupancy: "occupancy",
  occ: "occupancy",
  stories: "stories",
  story: "stories",
  ofstories: "stories",
  squarefeet: "square_feet",
  sqft: "square_feet",
  sqfeet: "square_feet",
  livingarea: "square_feet",
  livingareaheated: "square_feet",
  heatedsqft: "square_feet",
  bedrooms: "beds",
  beds: "beds",
  ofbedrooms: "beds",
  bathrooms: "baths",
  baths: "baths",
  ofbathrooms: "baths",
  coveragea: "coverage_a",
  cova: "coverage_a",
  dwelling: "coverage_a",
  dwellinglimit: "coverage_a",
  coverageadwelling: "coverage_a",
  coveragebotherstructures: "coverage_b",
  coverageb: "coverage_b",
  covb: "coverage_b",
  otherstructures: "coverage_b",
  coveragecpersonalproperty: "coverage_c",
  coveragec: "coverage_c",
  covc: "coverage_c",
  personalproperty: "coverage_c",
  contents: "coverage_c",
  coveragedlossofuse: "coverage_d",
  coveraged: "coverage_d",
  covd: "coverage_d",
  lossofuse: "coverage_d",
  additionallivingexpense: "coverage_d",
  ale: "coverage_d",
  hurricanedeductible: "hurricane_deductible",
  hurricaneded: "hurricane_deductible",
  hurricane: "hurricane_deductible",
  aopdeductible: "aop_deductible",
  aop: "aop_deductible",
  allotherperils: "aop_deductible",
  allotherperilsdeductible: "aop_deductible",
  winddeductible: "wind_deductible",
  windhail: "wind_deductible",
  roofyear: "roof_year",
  roofyr: "roof_year",
  yearofroof: "roof_year",
  roofinstalled: "roof_year",
  roofageyear: "roof_year",
  roofcovering: "roof_covering",
  roofcov: "roof_covering",
  rooftype: "roof_covering",
  roofmaterial: "roof_covering",
  roofshape: "roof_shape",
  roofgeometry: "roof_shape",
  openingprotection: "opening_protection",
  opnprot: "opening_protection",
  shutters: "opening_protection",
  pool: "pool",
  swimmingpool: "pool",
  protectionclass: "protection_class",
  protclass: "protection_class",
  ppc: "protection_class",
  milestocoast: "miles_to_coast",
  milestowater: "miles_to_coast",
  milestoshore: "miles_to_coast",
  mitocoast: "miles_to_coast",
  mobilehome: "mobile_home",
  manufactured: "mobile_home",
  manufacturedhome: "mobile_home",
  replacementcost: "replacement_cost_estimate",
  replacementcostestimate: "replacement_cost_estimate",
  rce: "replacement_cost_estimate",
  msb: "replacement_cost_estimate",
  currentcarrier: "current_carrier",
  incumbent: "current_carrier",
  incumbentcarrier: "current_carrier",
  expiringcarrier: "current_carrier",
  company: "current_carrier",
  insurancecompany: "current_carrier",
  writingcompany: "current_carrier",
  currentpremium: "current_premium",
  premium: "current_premium",
  annualpremium: "current_premium",
  totalpremium: "current_premium",
  effectivedate: "effective_date",
  policyeffective: "effective_date",
  inception: "effective_date",
  expirationdate: "expiration_date",
  policyexpiration: "expiration_date",
  expires: "expiration_date",
  policynumber: "policy_number",
  policy: "policy_number",
  policyno: "policy_number",
  form: "form",
  policyform: "form",
  hoform: "form",
  namedinsured: "named_insured",
  primarynamedinsured: "named_insured",
  insured: "named_insured",
  mortgagee: "mortgagee",
  mortgageeclause: "mortgagee",
  firstmortgagee: "mortgagee",
  floodzone: "flood_zone",
  femazone: "flood_zone",
  nfipzone: "flood_zone",
  fourpointdate: "four_point_date",
  "4pointdate": "four_point_date",
  fourpointinspectiondate: "four_point_date",
  fourpointresult: "four_point_result",
  "4pointresult": "four_point_result",
  fourpointstatus: "four_point_result",
  windmitform: "wind_mit_form",
  windmitigation: "wind_mit_form",
  windmitigationform: "wind_mit_form",
  oirb1802: "wind_mit_form",
  oirb11802: "wind_mit_form",
  vin: "vin",
  vehicleyear: "vehicle_year",
  year: "vehicle_year",
  make: "vehicle_make",
  vehiclemake: "vehicle_make",
  model: "vehicle_model",
  vehiclemodel: "vehicle_model",
  usage: "vehicle_usage",
  vehicleusage: "vehicle_usage",
  garagingzip: "garaging_zip",
  garagingaddress: "garaging_address",
  bilimits: "liability_bi",
  bodilyinjury: "liability_bi",
  liabilitybi: "liability_bi",
  pdlimit: "liability_pd",
  propertydamage: "liability_pd",
  umuim: "um_uim",
  uninsuredmotorist: "um_uim",
  pip: "pip",
  compdeductible: "comp_deductible",
  comprehensive: "comp_deductible",
  collisiondeductible: "collision_deductible",
  collision: "collision_deductible",
};

export function normalizeLabel(raw: string): string {
  return raw.toLowerCase().replace(/[^a-z0-9]+/g, "");
}

export function aliasToKey(rawLabel: string): string | null {
  const compact = normalizeLabel(rawLabel);
  if (!compact) return null;
  if (LABEL_ALIASES[compact]) return LABEL_ALIASES[compact];
  const stripped = compact.replace(/^(the|current|expiring)/, "");
  return LABEL_ALIASES[stripped] ?? null;
}

export function isBlockedExtractKey(key: string): boolean {
  return /ssn|socialsecurity|taxid|fein|claim/.test(key.replace(/_/g, ""));
}

export function looksLikeSsn(value: string): boolean {
  return /\b\d{3}-\d{2}-\d{4}\b/.test(value);
}
