import type { ShopLine } from "@/lib/domain";
import type { QuoteSheetFieldValue } from "@/lib/db/schema";
import {
  APPLICANT_CORE_FIELDS,
  CO_APPLICANT_FIELDS,
  ENTITY_TYPE_OPTIONS,
  GENDER_OPTIONS,
  OCCUPATION_OPTIONS,
  type QuoteFieldDef,
} from "./applicant-core";
import type { SheetProduct } from "./products";
import {
  AOP_DEDUCTIBLE_OPTIONS,
  CONSTRUCTION_OPTIONS,
  EXTERIOR_OPTIONS,
  FOUNDATION_OPTIONS,
  HURRICANE_DEDUCTIBLE_OPTIONS,
  DISTANCE_TO_HYDRANT_OPTIONS,
  DISTANCE_TO_STATION_OPTIONS,
  MONTHS_OCCUPIED_OPTIONS,
  OCCUPANCY_OPTIONS,
  OWN_RENT_OPTIONS,
  VEHICLE_OWNERSHIP_OPTIONS,
  VEHICLE_OWNERSHIP_LENGTH_OPTIONS,
  COMMUTE_DAYS_WEEK_OPTIONS,
  VEHICLE_LIENHOLDER_OPTIONS,
  PRIMARY_HEAT_OPTIONS,
  PRIMARY_PLUMBING_OPTIONS,
  USAGE_OPTIONS,
  AUTO_VEHICLE_USAGE_OPTIONS,
  AUTO_CURRENTLY_INSURED_OPTIONS,
  AUTO_ANNUAL_MILES_OPTIONS,
  AUTO_INCIDENT_COUNT_OPTIONS,
  AUTO_HOUSEHOLD_RELATIONSHIP_OPTIONS,
  AUTO_HOUSEHOLD_STATUS_OPTIONS,
  AUTO_HOUSEHOLD_EXCLUDE_REASON_OPTIONS,
  AUTO_HOUSEHOLD_SEPARATE_POLICY_STATUS_OPTIONS,
  WIND_HAIL_DEDUCTIBLE_OPTIONS,
  YES_NO_OPTIONS,
  BOP_CONSTRUCTION_OPTIONS,
  GL_CLAIMS_BASIS_OPTIONS,
  GL_AGGREGATE_LIMIT_OPTIONS,
  GL_OCCURRENCE_LIMIT_OPTIONS,
  FLOOD_OCCUPANCY_OPTIONS,
  FLOOD_FOUNDATION_OPTIONS,
  applyMasterSheetDefaults,
} from "./sheet-defaults";

export type { QuoteFieldDef } from "./applicant-core";
export {
  APPLICANT_CORE_FIELDS,
  CO_APPLICANT_FIELDS,
  CO_APPLICANT_RELATIONSHIP_OPTIONS,
  ENTITY_TYPE_OPTIONS,
  GENDER_OPTIONS,
  MARITAL_STATUS_OPTIONS,
  OCCUPATION_OPTIONS,
  RELATIONSHIP_TO_INSURED_OPTIONS,
} from "./applicant-core";

const HO_LL = ["homeowners", "landlord"] as const;
const RENT = ["renters"] as const;
const LL = ["landlord"] as const;

export const HOME_FIELDS: QuoteFieldDef[] = [
  { key: "address1", label: "Property address", group: "Property", extractKey: "address" },
  { key: "city", label: "City", group: "Property", extractKey: "city" },
  { key: "county", label: "County", group: "Property", extractKey: "county" },
  { key: "state", label: "State", group: "Property", extractKey: "state" },
  { key: "zip", label: "ZIP", group: "Property", extractKey: "zip" },
  { key: "mailing_address", label: "Mailing address", group: "Property", extractKey: "mailing_address" },
  { key: "legal_description", label: "Legal description", group: "Property" },
  { key: "parcel_id", label: "Parcel ID", group: "Property" },
  { key: "assessed_value", label: "Assessed value", group: "Property", input: "number" },
  { key: "land_value", label: "Land value", group: "Property", input: "number" },
  { key: "improvement_value", label: "Improvement value", group: "Property", input: "number" },
  { key: "sale_price", label: "Sale price", group: "Property", input: "number" },
  { key: "assessment_year", label: "Assessment year", group: "Property", input: "number" },
  { key: "homestead", label: "Homestead", group: "Property" },
  { key: "zoning", label: "Zoning", group: "Property" },
  { key: "land_use", label: "Land use", group: "Property" },
  { key: "records_check", label: "Records check", group: "Property", input: "textarea" },
  { key: "subdivision", label: "Subdivision", group: "Property" },
  { key: "year_purchased", label: "Year purchased", group: "Property", input: "number" },
  { key: "occupancy", label: "Occupancy", group: "Property", input: "select", options: [...OCCUPANCY_OPTIONS], extractKey: "occupancy" },
  { key: "usage", label: "Usage", group: "Property", input: "select", options: [...USAGE_OPTIONS], extractKey: "usage" },
  { key: "months_occupied", label: "Months occupied", group: "Property", input: "select", options: [...MONTHS_OCCUPIED_OPTIONS], extractKey: "months_occupied" },
  { key: "number_of_families", label: "Number of families", group: "Property", input: "number" },
  { key: "year_built", label: "Year built", group: "Dwelling", input: "number", extractKey: "year_built", products: [...HO_LL] },
  { key: "year_effective", label: "Effective year", group: "Dwelling", input: "number", products: [...HO_LL] },
  { key: "stories", label: "Stories", group: "Dwelling", input: "number", extractKey: "stories", products: [...HO_LL] },
  { key: "square_feet", label: "Square footage", group: "Dwelling", input: "number", extractKey: "square_feet", products: [...HO_LL] },
  { key: "beds", label: "Bedrooms", group: "Dwelling", input: "number", extractKey: "beds" },
  { key: "baths", label: "Bathrooms", group: "Dwelling", input: "number", extractKey: "baths" },
  { key: "construction", label: "Construction", group: "Dwelling", input: "select", options: [...CONSTRUCTION_OPTIONS], extractKey: "construction", products: [...HO_LL] },
  { key: "exterior", label: "Exterior", group: "Dwelling", input: "select", options: [...EXTERIOR_OPTIONS], extractKey: "exterior", products: [...HO_LL] },
  { key: "foundation", label: "Foundation", group: "Dwelling", input: "select", options: [...FOUNDATION_OPTIONS], products: [...HO_LL] },
  { key: "living_units", label: "Living units", group: "Dwelling", input: "number", products: [...HO_LL] },
  { key: "basement", label: "Basement", group: "Dwelling", input: "select", options: [...YES_NO_OPTIONS], products: [...HO_LL] },
  { key: "garage_type", label: "Garage", group: "Dwelling", extractKey: "garage", products: [...HO_LL] },
  { key: "carport", label: "Carport", group: "Dwelling", input: "select", options: [...YES_NO_OPTIONS], products: [...HO_LL] },
  { key: "roof_year", label: "Roof year", group: "Roof / wind", input: "number", extractKey: "roof_year", products: [...HO_LL] },
  { key: "roof_covering", label: "Roof covering", group: "Roof / wind", extractKey: "roof_covering", products: [...HO_LL] },
  { key: "roof_shape", label: "Roof shape", group: "Roof / wind", extractKey: "roof_shape", products: [...HO_LL] },
  { key: "roof_deck", label: "Roof deck", group: "Roof / wind", extractKey: "roof_deck", products: [...HO_LL] },
  { key: "roof_deck_attachment", label: "Roof deck attachment", group: "Roof / wind", extractKey: "roof_deck_attachment", products: [...HO_LL] },
  { key: "roof_to_wall", label: "Roof-to-wall connection", group: "Roof / wind", extractKey: "roof_to_wall", products: [...HO_LL] },
  {
    key: "opening_protection",
    label: "Opening protection",
    group: "Roof / wind",
    extractKey: "opening_protection",
    products: [...HO_LL],
  },
  { key: "secondary_water", label: "Secondary water resistance", group: "Roof / wind", extractKey: "swr", products: [...HO_LL] },
  { key: "terrain", label: "Terrain", group: "Roof / wind", extractKey: "terrain", products: [...HO_LL] },
  { key: "wind_speed", label: "Design wind speed", group: "Roof / wind", extractKey: "wind_speed", products: [...HO_LL] },
  { key: "wind_mit_form", label: "Wind mit form", group: "Roof / wind", extractKey: "wind_mit_form", products: [...HO_LL] },
  { key: "wind_mit_date", label: "Wind mit date", group: "Roof / wind", extractKey: "wind_mit_date", products: [...HO_LL] },
  { key: "wind_mit_inspector", label: "Wind mit inspector", group: "Roof / wind", extractKey: "wind_mit_inspector", products: [...HO_LL] },
  { key: "building_code", label: "Building code", group: "Roof / wind", extractKey: "building_code", products: [...HO_LL] },
  { key: "inspection_company", label: "Inspection company", group: "Roof / wind", extractKey: "inspection_company", products: [...HO_LL] },
  { key: "license_or_certificate_number", label: "License or certificate #", group: "Roof / wind", extractKey: "license_or_certificate_number", products: [...HO_LL] },
  { key: "date_inspected", label: "Date inspected", group: "4-point", extractKey: "date_inspected", products: [...HO_LL] },
  {
    key: "protection_class",
    label: "Protection class",
    group: "Protection",
    extractKey: "protection_class",
  },
  { key: "fire_district", label: "Fire district", group: "Protection" },
  { key: "hydrant", label: "Distance to hydrant", group: "Protection", input: "select", options: [...DISTANCE_TO_HYDRANT_OPTIONS] },
  { key: "miles_to_fire_station", label: "Distance to station", group: "Protection", input: "select", options: [...DISTANCE_TO_STATION_OPTIONS] },
  { key: "central_alarm", label: "Central alarm", group: "Protection", input: "select", options: [...YES_NO_OPTIONS] },
  { key: "sprinkler", label: "Sprinkler", group: "Protection", input: "select", options: [...YES_NO_OPTIONS] },
  { key: "smoke_detectors", label: "Smoke detectors", group: "Protection", input: "select", options: [...YES_NO_OPTIONS] },
  { key: "deadbolts", label: "Deadbolts", group: "Protection", input: "select", options: [...YES_NO_OPTIONS], extractKey: "deadbolts" },
  {
    key: "miles_to_coast",
    label: "Miles to coast",
    group: "Coastal / flood",
    input: "number",
    extractKey: "miles_to_coast",
  },
  { key: "flood_zone", label: "Flood zone", group: "Coastal / flood", extractKey: "flood_zone" },
  { key: "firm_panel", label: "FIRM panel", group: "Coastal / flood" },
  { key: "firm_effective_date", label: "FIRM effective date", group: "Coastal / flood" },
  { key: "bfe", label: "Base flood elevation", group: "Coastal / flood", input: "number" },
  { key: "flood_policy", label: "Flood policy in force", group: "Coastal / flood" },
  { key: "elevation", label: "Elevation", group: "Coastal / flood" },
  { key: "pool", label: "Pool", group: "Hazards", input: "select", options: [...YES_NO_OPTIONS], extractKey: "pool" },
  { key: "pool_fence", label: "Pool fence", group: "Hazards", input: "select", options: [...YES_NO_OPTIONS] },
  { key: "trampoline", label: "Trampoline", group: "Hazards", input: "select", options: [...YES_NO_OPTIONS] },
  { key: "animals", label: "Animals", group: "Hazards", input: "select", options: [...YES_NO_OPTIONS] },
  { key: "dog_breed", label: "Dog breed", group: "Hazards", input: "select", options: [...YES_NO_OPTIONS] },
  { key: "business_on_premises", label: "Business on premises", group: "Hazards", input: "select", options: [...YES_NO_OPTIONS] },
  { key: "mobile_home", label: "Mobile / manufactured", group: "Hazards", input: "select", options: [...YES_NO_OPTIONS], extractKey: "mobile_home", products: [...HO_LL] },
  { key: "acres", label: "Acres", group: "Hazards", input: "number" },
  { key: "four_point_date", label: "4-point date", group: "4-point", extractKey: "four_point_date", products: [...HO_LL] },
  { key: "four_point_result", label: "4-point result", group: "4-point", extractKey: "four_point_result", products: [...HO_LL] },
  { key: "plumbing_year", label: "Plumbing year", group: "4-point", input: "number", extractKey: "plumbing_year", products: [...HO_LL] },
  { key: "electrical_year", label: "Electrical year", group: "4-point", input: "number", extractKey: "electrical_year", products: [...HO_LL] },
  { key: "electrical_updated", label: "Electrical last updated", group: "4-point", input: "number", extractKey: "electrical_updated", products: [...HO_LL] },
  { key: "electrical_circuit_amps", label: "Electrical Circuit Amps", group: "4-point", input: "number", extractKey: "electrical_circuit_amps", products: [...HO_LL] },
  { key: "primary_plumbing_type", label: "Primary plumbing type", group: "4-point", input: "select", options: [...PRIMARY_PLUMBING_OPTIONS], extractKey: "primary_plumbing_type", products: [...HO_LL] },
  { key: "water_heater_year", label: "Water heater year", group: "4-point", input: "number", extractKey: "water_heater_year", products: [...HO_LL] },
  { key: "primary_heat", label: "Primary heat", group: "4-point", input: "select", options: [...PRIMARY_HEAT_OPTIONS], extractKey: "primary_heat", products: [...HO_LL] },
  { key: "hvac_year", label: "HVAC year", group: "4-point", input: "number", extractKey: "hvac_year", products: [...HO_LL] },
  { key: "roof_condition", label: "Roof condition (4-point)", group: "4-point", products: [...HO_LL] },
  { key: "coverage_a", label: "Coverage A (dwelling)", group: "Coverages", input: "number", extractKey: "coverage_a", products: [...HO_LL] },
  { key: "coverage_b", label: "Coverage B (other structures)", group: "Coverages", input: "number", extractKey: "coverage_b", products: [...HO_LL] },
  { key: "coverage_c", label: "Coverage C (contents)", group: "Coverages", input: "number", extractKey: "coverage_c" },
  { key: "coverage_d", label: "Coverage D (loss of use)", group: "Coverages", input: "number", extractKey: "coverage_d" },
  { key: "coverage_e", label: "Coverage E (liability)", group: "Coverages", input: "number", extractKey: "coverage_e" },
  { key: "coverage_f", label: "Coverage F (medical payments)", group: "Coverages", input: "number", extractKey: "coverage_f" },
  { key: "ordinance_or_law", label: "Ordinance or law", group: "Coverages", extractKey: "ordinance_or_law" },
  { key: "water_backup", label: "Water backup", group: "Coverages", extractKey: "water_backup" },
  {
    key: "hurricane_deductible",
    label: "Hurricane deductible",
    group: "Coverages",
    input: "select",
    options: [...HURRICANE_DEDUCTIBLE_OPTIONS],
    extractKey: "hurricane_deductible",
  },
  { key: "aop_deductible", label: "AOP deductible", group: "Coverages", input: "select", options: [...AOP_DEDUCTIBLE_OPTIONS], extractKey: "aop_deductible" },
  {
    key: "wind_hail_deductible",
    label: "Wind / hail deductible",
    group: "Coverages",
    input: "select",
    options: [...WIND_HAIL_DEDUCTIBLE_OPTIONS],
    extractKey: "wind_hail_deductible",
  },
  { key: "sinkhole_deductible", label: "Sinkhole deductible", group: "Coverages" },
  {
    key: "replacement_cost_estimate",
    label: "RCE / MSB (not Zillow)",
    group: "Coverages",
    input: "number",
    extractKey: "replacement_cost_estimate",
    products: [...HO_LL],
  },
  { key: "rce_source", label: "RCE source", group: "Coverages", products: [...HO_LL] },
  { key: "named_insured", label: "Named insured (from dec)", group: "Current policy", extractKey: "named_insured" },
  { key: "current_policy_named_insured", label: "Name insured (policy)", group: "Current policy", extractKey: "current_policy_named_insured" },
  {
    key: "secondary_named_insured",
    label: "Additional named insured (from dec)",
    group: "Current policy",
    extractKey: "secondary_named_insured",
  },
  { key: "current_carrier", label: "Current carrier", group: "Current policy", extractKey: "current_carrier" },
  { key: "policy_number", label: "Policy number", group: "Current policy", extractKey: "policy_number" },
  { key: "form", label: "Form", group: "Current policy", extractKey: "form" },
  { key: "current_premium", label: "Current premium", group: "Current policy", input: "number", extractKey: "current_premium" },
  { key: "effective_date", label: "Effective date", group: "Current policy", extractKey: "effective_date" },
  { key: "expiration_date", label: "Expiration date", group: "Current policy", extractKey: "expiration_date" },
  { key: "years_with_carrier", label: "Years with carrier", group: "Current policy", input: "number" },
  { key: "claims_5yr", label: "Claims last 5 years", group: "Current policy", input: "number" },
  { key: "mortgagee_name", label: "Mortgagee", group: "Mortgagee", extractKey: "mortgagee" },
  { key: "mortgagee_address", label: "Mortgagee address", group: "Mortgagee", extractKey: "mortgagee_address" },
  { key: "loan_number", label: "Loan number", group: "Mortgagee", extractKey: "loan_number" },
  { key: "tenant_name", label: "Tenant name", group: "Landlord", products: [...LL] },
  { key: "lease_term", label: "Lease term", group: "Landlord", products: [...LL] },
  { key: "landlord_liability", label: "Landlord liability", group: "Landlord", products: [...LL] },
  { key: "loss_of_rents", label: "Loss of rents", group: "Landlord", products: [...LL] },
  { key: "contents_limit", label: "Contents limit", group: "Renters", input: "number", products: [...RENT] },
  { key: "renters_liability", label: "Renters liability", group: "Renters", products: [...RENT] },
  { key: "additional_living", label: "Additional living expense", group: "Renters", products: [...RENT] },
  { key: "notes", label: "Shop notes", group: "Notes", input: "textarea" },
];

export const AUTO_FIELDS: QuoteFieldDef[] = [
  {
    key: "own_rent",
    label: "Own / Rent",
    group: "Residence",
    input: "select",
    options: [...OWN_RENT_OPTIONS],
  },
  {
    key: "years_at_address",
    label: "Years at address",
    group: "Residence",
    input: "number",
  },
  {
    key: "address_same_6_months",
    label: "Same address 6+ months?",
    group: "Residence",
    input: "select",
    options: [...YES_NO_OPTIONS],
  },
  {
    key: "prior_address",
    label: "Prior address (if No)",
    group: "Residence",
  },
  { key: "vin", label: "VIN", group: "Vehicle" },
  { key: "vehicle_year", label: "Year", group: "Vehicle", input: "number" },
  { key: "vehicle_make", label: "Make", group: "Vehicle" },
  { key: "vehicle_model", label: "Model", group: "Vehicle" },
  { key: "vehicle_body_class", label: "Body class", group: "Vehicle" },
  { key: "vehicle_fuel_type", label: "Fuel type", group: "Vehicle" },
  { key: "vehicle_engine", label: "Engine", group: "Vehicle" },
  { key: "vehicle_usage", label: "Usage", group: "Vehicle", input: "select", options: [...AUTO_VEHICLE_USAGE_OPTIONS] },
  {
    key: "vehicle_ownership",
    label: "Ownership",
    group: "Vehicle",
    input: "select",
    options: [...VEHICLE_OWNERSHIP_OPTIONS],
  },
  {
    key: "vehicle_ownership_length",
    label: "Length of ownership",
    group: "Vehicle",
    input: "select",
    options: [...VEHICLE_OWNERSHIP_LENGTH_OPTIONS],
  },
  {
    key: "vehicle_lienholder",
    label: "Lienholder",
    group: "Vehicle",
    input: "select",
    options: [...VEHICLE_LIENHOLDER_OPTIONS],
  },
  {
    key: "vehicle_lienholder_other",
    label: "Lienholder (other / custom)",
    group: "Vehicle",
  },
  {
    key: "vehicle_purchase_date",
    label: "Purchase date",
    group: "Vehicle",
  },
  {
    key: "purchased_new",
    label: "Purchased new?",
    group: "Vehicle",
    input: "select",
    options: [...YES_NO_OPTIONS],
  },
  {
    key: "original_cost_new",
    label: "Original cost new (OCN)",
    group: "Vehicle",
    input: "number",
    // Portals also call this OCN / cost new — leave blank OK (no forced default).
  },
  {
    key: "annual_miles",
    label: "Annual miles",
    group: "Vehicle",
    input: "select",
    options: [...AUTO_ANNUAL_MILES_OPTIONS],
  },
  {
    key: "commute_days_week",
    label: "Commute days / week",
    group: "Vehicle",
    input: "select",
    options: [...COMMUTE_DAYS_WEEK_OPTIONS],
  },
  {
    key: "commute_miles_daily",
    label: "Miles driven daily",
    group: "Vehicle",
    input: "number",
  },
  {
    key: "rideshare",
    label: "Used for rideshare (Uber / Lyft)?",
    group: "Vehicle",
    input: "select",
    options: [...YES_NO_OPTIONS],
  },
  {
    key: "aftermarket_parts",
    label: "Any non-factory / aftermarket parts?",
    group: "Vehicle",
    input: "select",
    options: [...YES_NO_OPTIONS],
  },
  { key: "garaging_zip", label: "Garaging ZIP", group: "Vehicle" },
  { key: "garaging_address", label: "Garaging address", group: "Vehicle" },
  { key: "vehicle_2_vin", label: "Vehicle 2 VIN", group: "Vehicle" },
  { key: "vehicle_2_year", label: "Vehicle 2 year", group: "Vehicle", input: "number" },
  { key: "vehicle_2_make", label: "Vehicle 2 make", group: "Vehicle" },
  { key: "vehicle_2_model", label: "Vehicle 2 model", group: "Vehicle" },
  { key: "vehicle_2_body_class", label: "Vehicle 2 body class", group: "Vehicle" },
  { key: "vehicle_2_fuel_type", label: "Vehicle 2 fuel type", group: "Vehicle" },
  { key: "vehicle_2_engine", label: "Vehicle 2 engine", group: "Vehicle" },
  { key: "driver_1_name", label: "Driver 1 name", group: "Drivers" },
  { key: "driver_1_dob", label: "Driver 1 DOB", group: "Drivers" },
  {
    key: "driver_1_gender",
    label: "Driver 1 gender",
    group: "Drivers",
    input: "select",
    options: [...GENDER_OPTIONS],
  },
  {
    key: "driver_1_occupation",
    label: "Driver 1 occupation",
    group: "Drivers",
    input: "select",
    options: [...OCCUPATION_OPTIONS],
  },
  { key: "driver_1_license", label: "Driver 1 license", group: "Drivers" },
  { key: "driver_1_status", label: "Driver 1 status", group: "Drivers" },
  { key: "driver_1_years_licensed", label: "Driver 1 years licensed", group: "Drivers", input: "number" },
  { key: "driver_2_name", label: "Driver 2 name", group: "Drivers" },
  { key: "driver_2_dob", label: "Driver 2 DOB", group: "Drivers" },
  { key: "driver_2_license", label: "Driver 2 license", group: "Drivers" },
  {
    key: "accidents_3yr",
    label: "Accidents last 3 years",
    group: "Driving record",
    input: "select",
    options: [...AUTO_INCIDENT_COUNT_OPTIONS],
  },
  {
    key: "violations_3yr",
    label: "Violations last 3 years",
    group: "Driving record",
    input: "select",
    options: [...AUTO_INCIDENT_COUNT_OPTIONS],
  },
  {
    key: "clean_record",
    label: "Clean record (no reportable accidents/violations)?",
    group: "Driving record",
    input: "select",
    options: [...YES_NO_OPTIONS],
  },
  {
    key: "incident_details",
    label: "Incident details (if any)",
    group: "Driving record",
  },
  {
    key: "reportable_incidents",
    label: "Reportable incidents (via MVR pull — do not paste manually)",
    group: "Driving record",
    input: "select",
    options: [...YES_NO_OPTIONS],
  },
  {
    key: "permission_pull_driving_history",
    label: "Permission to pull driving history / MVR",
    group: "Authorizations",
    input: "select",
    options: [...YES_NO_OPTIONS],
  },
  {
    key: "permission_pull_credit_history",
    label: "Permission to pull credit history",
    group: "Authorizations",
    input: "select",
    options: [...YES_NO_OPTIONS],
  },
  // Slots — UI uses RepeatableUnitBlocks (Household); keys keep catalog group present.
  { key: "household_1_name", label: "Household 1 name", group: "Household" },
  { key: "household_1_dob", label: "Household 1 DOB", group: "Household" },
  {
    key: "household_1_relationship",
    label: "Household 1 relationship",
    group: "Household",
    input: "select",
    options: [...AUTO_HOUSEHOLD_RELATIONSHIP_OPTIONS],
  },
  {
    key: "household_1_status",
    label: "Household 1 status",
    group: "Household",
    input: "select",
    options: [...AUTO_HOUSEHOLD_STATUS_OPTIONS],
  },
  {
    key: "household_1_exclude_reason",
    label: "Household 1 exclude reason (Non-Rated/Excluded)",
    group: "Household",
    input: "select",
    options: [...AUTO_HOUSEHOLD_EXCLUDE_REASON_OPTIONS],
  },
  {
    key: "household_1_separate_auto_policy",
    label: "Household 1 has separate auto policy",
    group: "Household",
    input: "select",
    options: [...YES_NO_OPTIONS],
  },
  {
    key: "household_1_separate_policy_status",
    label: "Household 1 separate policy status",
    group: "Household",
    input: "select",
    options: [...AUTO_HOUSEHOLD_SEPARATE_POLICY_STATUS_OPTIONS],
  },
  {
    key: "household_1_age_first_licensed",
    label: "Household 1 age first licensed",
    group: "Household",
  },
  {
    key: "household_1_suspension_5yr",
    label: "Household 1 suspension in last 5 years",
    group: "Household",
    input: "select",
    options: [...YES_NO_OPTIONS],
  },
  { key: "liability_bi", label: "BI limits", group: "Coverages" },
  { key: "liability_pd", label: "PD limit", group: "Coverages" },
  { key: "um_uim", label: "UM / UIM", group: "Coverages" },
  { key: "pip", label: "PIP", group: "Coverages" },
  { key: "comp_deductible", label: "Comp deductible", group: "Coverages" },
  { key: "collision_deductible", label: "Collision deductible", group: "Coverages" },
  { key: "motorcycle_cc", label: "Engine CC", group: "Motorcycle", products: ["motorcycle"] },
  { key: "motorcycle_type", label: "Motorcycle type", group: "Motorcycle", products: ["motorcycle"] },
  { key: "endorsed_rider", label: "Endorsed rider", group: "Motorcycle", products: ["motorcycle"] },
  { key: "radius", label: "Radius", group: "Commercial auto", products: ["commercial_auto"] },
  { key: "gvw", label: "GVW", group: "Commercial auto", products: ["commercial_auto"] },
  { key: "vehicle_class", label: "Vehicle class", group: "Commercial auto", products: ["commercial_auto"] },
  { key: "fleet_size", label: "Fleet size", group: "Commercial auto", input: "number", products: ["commercial_auto"] },
  { key: "current_carrier", label: "Current carrier", group: "Current policy", extractKey: "current_carrier" },
  { key: "current_premium", label: "Current premium", group: "Current policy", input: "number" },
  { key: "years_with_carrier", label: "Years with carrier", group: "Current policy", input: "number" },
  { key: "effective_date", label: "Effective date", group: "Current policy", extractKey: "effective_date" },
  { key: "expiration_date", label: "Expiration date", group: "Current policy", extractKey: "expiration_date" },
  { key: "policy_number", label: "Current policy ID", group: "Current policy", extractKey: "policy_number" },
  {
    key: "currently_insured",
    label: "Currently insured",
    group: "Current policy",
    input: "select",
    options: [...AUTO_CURRENTLY_INSURED_OPTIONS],
  },
  { key: "notes", label: "Shop notes", group: "Notes", input: "textarea" },
];

export const REC_RV_FIELDS: QuoteFieldDef[] = [
  { key: "unit_year", label: "Year", group: "Unit", input: "number" },
  { key: "make", label: "Make", group: "Unit" },
  { key: "model", label: "Model", group: "Unit" },
  { key: "vin", label: "VIN / HIN", group: "Unit" },
  { key: "value", label: "Value", group: "Unit", input: "number" },
  { key: "usage", label: "Usage", group: "Unit" },
  { key: "storage", label: "Storage", group: "Unit" },
  { key: "length_feet", label: "Length (ft)", group: "Unit", input: "number" },
  { key: "slideouts", label: "Slide-outs", group: "Unit" },
  { key: "full_timer", label: "Full-timer", group: "Unit" },
  { key: "current_carrier", label: "Current carrier", group: "Current policy" },
  { key: "notes", label: "Notes", group: "Notes", input: "textarea" },
];

export const FLOOD_FIELDS: QuoteFieldDef[] = [
  // Property / NFIP map (FEMA FF-206 + Floodsmart app)
  { key: "property_address", label: "Property address", group: "Property", extractKey: "property_address" },
  { key: "flood_zone", label: "Flood zone", group: "Property", extractKey: "flood_zone" },
  { key: "community_number", label: "NFIP community number", group: "Property" },
  { key: "firm_panel", label: "FIRM panel", group: "Property" },
  { key: "firm_effective_date", label: "FIRM effective date", group: "Property" },
  {
    key: "flood_occupancy",
    label: "Building occupancy",
    group: "Property",
    input: "select",
    options: [...FLOOD_OCCUPANCY_OPTIONS],
  },
  { key: "year_built", label: "Year built", group: "Property", input: "number", extractKey: "year_built" },
  { key: "building_sqft", label: "Building square footage", group: "Property", input: "number" },
  { key: "number_of_floors", label: "Number of floors (excl. basement)", group: "Property", input: "number" },
  { key: "construction_type", label: "Construction type", group: "Property", input: "select", options: [...CONSTRUCTION_OPTIONS] },
  {
    key: "foundation",
    label: "Foundation type",
    group: "Foundation / elevation",
    input: "select",
    options: [...FLOOD_FOUNDATION_OPTIONS],
  },
  { key: "enclosure_present", label: "Enclosure / crawlspace present", group: "Foundation / elevation", input: "select", options: [...YES_NO_OPTIONS] },
  { key: "proper_flood_openings", label: "Proper flood openings / engineered openings", group: "Foundation / elevation", input: "select", options: [...YES_NO_OPTIONS] },
  { key: "flood_openings_count", label: "Number of flood openings", group: "Foundation / elevation", input: "number" },
  { key: "flood_openings_sq_in", label: "Total opening area (sq in)", group: "Foundation / elevation", input: "number" },
  { key: "enclosed_area_sqft", label: "Total enclosed area (sq ft)", group: "Foundation / elevation", input: "number" },
  { key: "elevation_certificate", label: "Elevation certificate on file", group: "Foundation / elevation", input: "select", options: [...YES_NO_OPTIONS] },
  { key: "ec_date", label: "Elevation certificate date", group: "Foundation / elevation" },
  { key: "building_diagram", label: "Building diagram number", group: "Foundation / elevation" },
  { key: "lag", label: "Lowest adjacent grade (ft)", group: "Foundation / elevation", input: "number" },
  { key: "lowest_floor", label: "Lowest floor elevation (ft)", group: "Foundation / elevation", input: "number" },
  { key: "first_floor_height", label: "First floor height (ft)", group: "Foundation / elevation", input: "number" },
  { key: "bfe", label: "Base flood elevation (BFE)", group: "Foundation / elevation", input: "number" },
  { key: "under_construction", label: "Building under construction", group: "Building", input: "select", options: [...YES_NO_OPTIONS] },
  { key: "substantially_improved", label: "Substantially improved", group: "Building", input: "select", options: [...YES_NO_OPTIONS] },
  { key: "over_water", label: "Building over water", group: "Building", input: "select", options: ["no", "partially", "entirely"] },
  { key: "floodproofed", label: "Properly floodproofed", group: "Building", input: "select", options: [...YES_NO_OPTIONS] },
  { key: "me_mitigation", label: "Machinery & equipment mitigation discount", group: "Building", input: "select", options: [...YES_NO_OPTIONS] },
  { key: "building_limit", label: "Building coverage", group: "Coverages", input: "number" },
  { key: "contents_limit", label: "Contents coverage", group: "Coverages", input: "number" },
  { key: "building_deductible", label: "Building deductible", group: "Coverages" },
  { key: "contents_deductible", label: "Contents deductible", group: "Coverages" },
  { key: "nfip_policy", label: "Current NFIP / flood policy number", group: "Current policy" },
  { key: "current_carrier", label: "Current carrier", group: "Current policy" },
  { key: "current_premium", label: "Current premium", group: "Current policy", input: "number" },
  { key: "expiration_date", label: "Expiration date", group: "Current policy" },
  { key: "notes", label: "Notes", group: "Notes", input: "textarea" },
];

export const UMBRELLA_FIELDS: QuoteFieldDef[] = [
  { key: "limit", label: "Umbrella limit", group: "Coverages" },
  { key: "underlying_home", label: "Underlying home", group: "Underlying" },
  { key: "underlying_auto", label: "Underlying auto", group: "Underlying" },
  { key: "um_uim", label: "UM / UIM", group: "Underlying" },
  { key: "current_carrier", label: "Current carrier", group: "Current policy" },
  { key: "notes", label: "Notes", group: "Notes", input: "textarea" },
];

export const LIFE_FIELDS: QuoteFieldDef[] = [
  { key: "face_amount", label: "Face amount", group: "CRM" },
  { key: "product_type", label: "Product type", group: "CRM" },
  { key: "notes", label: "Life notes (CRM only — no rating)", group: "CRM", input: "textarea" },
];

export const HEALTH_FIELDS: QuoteFieldDef[] = [
  { key: "plan_type", label: "Plan type", group: "CRM" },
  { key: "members", label: "Members", group: "CRM", input: "number" },
  { key: "notes", label: "Health notes (CRM only — no rating)", group: "CRM", input: "textarea" },
];

export const WC_FIELDS: QuoteFieldDef[] = [
  // ACORD 130–style template
  { key: "legal_name", label: "Legal entity name", group: "Business" },
  { key: "dba", label: "DBA", group: "Business" },
  { key: "fein", label: "FEIN", group: "Business" },
  { key: "entity_type", label: "Entity type", group: "Business", input: "select", options: [...ENTITY_TYPE_OPTIONS] },
  { key: "years_in_business", label: "Years in business", group: "Business", input: "number" },
  { key: "naics", label: "NAICS / SIC", group: "Business" },
  { key: "operations_description", label: "Description of operations", group: "Business", input: "textarea" },
  { key: "mailing_address", label: "Mailing address", group: "Business" },
  { key: "locations", label: "Locations (city / state)", group: "Business", input: "textarea" },
  { key: "states", label: "Governing state(s)", group: "Business" },
  { key: "class_code", label: "Class code 1", group: "Payroll by class" },
  { key: "class_description", label: "Class 1 description / duties", group: "Payroll by class" },
  { key: "payroll", label: "Class 1 estimated annual payroll", group: "Payroll by class", input: "number" },
  { key: "employees_ft", label: "Class 1 full-time employees", group: "Payroll by class", input: "number" },
  { key: "employees_pt", label: "Class 1 part-time employees", group: "Payroll by class", input: "number" },
  { key: "class_code_2", label: "Class code 2", group: "Payroll by class" },
  { key: "class_description_2", label: "Class 2 description / duties", group: "Payroll by class" },
  { key: "payroll_2", label: "Class 2 estimated annual payroll", group: "Payroll by class", input: "number" },
  { key: "class_code_3", label: "Class code 3", group: "Payroll by class" },
  { key: "class_description_3", label: "Class 3 description / duties", group: "Payroll by class" },
  { key: "payroll_3", label: "Class 3 estimated annual payroll", group: "Payroll by class", input: "number" },
  { key: "employees", label: "Total employees", group: "Risk", input: "number" },
  { key: "officers_included", label: "Officers included", group: "Risk", input: "select", options: [...YES_NO_OPTIONS] },
  { key: "owners_included", label: "Owners / partners included", group: "Risk", input: "select", options: [...YES_NO_OPTIONS] },
  { key: "experience_mod", label: "Experience mod (EMOD)", group: "Risk" },
  { key: "prior_carrier", label: "Prior WC carrier", group: "Current policy" },
  { key: "policy_number", label: "Current policy number", group: "Current policy" },
  { key: "expiration_date", label: "Expiration date", group: "Current policy" },
  { key: "current_premium", label: "Current premium", group: "Current policy", input: "number" },
  { key: "loss_history", label: "Loss history (3–5 yrs summary)", group: "Loss history", input: "textarea" },
  { key: "notes", label: "Notes", group: "Notes", input: "textarea" },
];

export const GL_FIELDS: QuoteFieldDef[] = [
  // ACORD 125/126–style template
  { key: "legal_name", label: "Legal entity name", group: "Business" },
  { key: "dba", label: "DBA", group: "Business" },
  { key: "fein", label: "FEIN", group: "Business" },
  { key: "entity_type", label: "Entity type", group: "Business", input: "select", options: [...ENTITY_TYPE_OPTIONS] },
  { key: "years_in_business", label: "Years in business", group: "Business", input: "number" },
  { key: "naics", label: "NAICS / SIC", group: "Business" },
  { key: "operations_description", label: "Description of operations", group: "Business", input: "textarea" },
  { key: "mailing_address", label: "Mailing / premises address", group: "Business" },
  { key: "annual_sales", label: "Annual sales / receipts", group: "Exposures", input: "number" },
  { key: "payroll", label: "Annual payroll", group: "Exposures", input: "number" },
  { key: "employees", label: "Employees", group: "Exposures", input: "number" },
  { key: "square_footage", label: "Occupied square footage", group: "Exposures", input: "number" },
  { key: "class_code", label: "ISO class code 1", group: "Schedule of hazards" },
  { key: "class_description", label: "Class 1 description", group: "Schedule of hazards" },
  { key: "premium_basis", label: "Class 1 premium basis (sales / payroll / area)", group: "Schedule of hazards" },
  { key: "exposure_amount", label: "Class 1 exposure amount", group: "Schedule of hazards", input: "number" },
  { key: "class_code_2", label: "ISO class code 2", group: "Schedule of hazards" },
  { key: "class_description_2", label: "Class 2 description", group: "Schedule of hazards" },
  { key: "class_code_3", label: "ISO class code 3", group: "Schedule of hazards" },
  {
    key: "claims_basis",
    label: "Claims basis",
    group: "Coverages",
    input: "select",
    options: [...GL_CLAIMS_BASIS_OPTIONS],
  },
  {
    key: "each_occurrence",
    label: "Each occurrence",
    group: "Coverages",
    input: "select",
    options: [...GL_OCCURRENCE_LIMIT_OPTIONS],
  },
  {
    key: "general_aggregate",
    label: "General aggregate",
    group: "Coverages",
    input: "select",
    options: [...GL_AGGREGATE_LIMIT_OPTIONS],
  },
  { key: "products_aggregate", label: "Products / completed ops aggregate", group: "Coverages" },
  { key: "personal_injury", label: "Personal & advertising injury", group: "Coverages" },
  { key: "damage_to_rented", label: "Damage to rented premises", group: "Coverages" },
  { key: "medical_expense", label: "Medical expense", group: "Coverages" },
  { key: "deductible", label: "Deductible", group: "Coverages" },
  { key: "subcontractors", label: "Uses subcontractors", group: "Contractors / products", input: "select", options: [...YES_NO_OPTIONS] },
  { key: "pct_subbed", label: "% of work subcontracted", group: "Contractors / products", input: "number" },
  { key: "products", label: "Manufactures / sells products", group: "Contractors / products", input: "select", options: [...YES_NO_OPTIONS] },
  { key: "current_carrier", label: "Current carrier", group: "Current policy" },
  { key: "policy_number", label: "Current policy number", group: "Current policy" },
  { key: "expiration_date", label: "Expiration date", group: "Current policy" },
  { key: "current_premium", label: "Current premium", group: "Current policy", input: "number" },
  { key: "loss_history", label: "Loss history summary", group: "Loss history", input: "textarea" },
  { key: "notes", label: "Notes", group: "Notes", input: "textarea" },
];

/** ACORD 160–style Businessowners (BOP) master sheet template. */
export const BOP_FIELDS: QuoteFieldDef[] = [
  { key: "legal_name", label: "Legal entity name", group: "Business" },
  { key: "dba", label: "DBA", group: "Business" },
  { key: "fein", label: "FEIN", group: "Business" },
  { key: "entity_type", label: "Entity type", group: "Business", input: "select", options: [...ENTITY_TYPE_OPTIONS] },
  { key: "years_in_business", label: "Years in business", group: "Business", input: "number" },
  { key: "naics", label: "NAICS / SIC", group: "Business" },
  { key: "operations_description", label: "Nature of business / operations", group: "Business", input: "textarea" },
  { key: "mailing_address", label: "Business address", group: "Business" },
  { key: "annual_sales", label: "Annual sales", group: "Exposures", input: "number" },
  { key: "payroll", label: "Annual payroll", group: "Exposures", input: "number" },
  { key: "employees", label: "Employees", group: "Exposures", input: "number" },
  { key: "square_footage", label: "Building / occupied sq ft", group: "Property", input: "number" },
  { key: "year_built", label: "Year built", group: "Property", input: "number" },
  {
    key: "construction_type",
    label: "Construction type",
    group: "Property",
    input: "select",
    options: [...BOP_CONSTRUCTION_OPTIONS],
  },
  { key: "protection_class", label: "Protection class", group: "Property" },
  { key: "stories", label: "Stories", group: "Property", input: "number" },
  { key: "occupancy", label: "Occupancy / use", group: "Property" },
  { key: "building_limit", label: "Building limit", group: "Property coverages", input: "number" },
  { key: "bpp_limit", label: "Business personal property (BPP)", group: "Property coverages", input: "number" },
  { key: "business_income", label: "Business income / extra expense", group: "Property coverages" },
  { key: "property_deductible", label: "Property deductible", group: "Property coverages" },
  {
    key: "each_occurrence",
    label: "Liability each occurrence",
    group: "Liability",
    input: "select",
    options: [...GL_OCCURRENCE_LIMIT_OPTIONS],
  },
  {
    key: "general_aggregate",
    label: "Liability aggregate",
    group: "Liability",
    input: "select",
    options: [...GL_AGGREGATE_LIMIT_OPTIONS],
  },
  { key: "medical_expense", label: "Medical expense", group: "Liability" },
  { key: "damage_to_rented", label: "Damage to rented premises", group: "Liability" },
  { key: "hired_non_owned_auto", label: "Hired / non-owned auto", group: "Liability", input: "select", options: [...YES_NO_OPTIONS] },
  { key: "class_code", label: "BOP / liability class code", group: "Classification" },
  { key: "class_description", label: "Class description", group: "Classification" },
  { key: "current_carrier", label: "Current carrier", group: "Current policy" },
  { key: "policy_number", label: "Current policy number", group: "Current policy" },
  { key: "expiration_date", label: "Expiration date", group: "Current policy" },
  { key: "current_premium", label: "Current premium", group: "Current policy", input: "number" },
  { key: "loss_history", label: "Loss history summary", group: "Loss history", input: "textarea" },
  { key: "notes", label: "Notes", group: "Notes", input: "textarea" },
];

const CATALOG: Record<ShopLine, QuoteFieldDef[]> = {
  home: HOME_FIELDS,
  auto: AUTO_FIELDS,
  rec_rv: REC_RV_FIELDS,
  flood: FLOOD_FIELDS,
  umbrella: UMBRELLA_FIELDS,
  life: LIFE_FIELDS,
  health: HEALTH_FIELDS,
  workers_comp: WC_FIELDS,
  general_liability: GL_FIELDS,
  bop: BOP_FIELDS,
};

function dedupeFields(fields: QuoteFieldDef[]): QuoteFieldDef[] {
  const seen = new Set<string>();
  const out: QuoteFieldDef[] = [];
  for (const field of fields) {
    if (seen.has(field.key)) continue;
    seen.add(field.key);
    out.push(field);
  }
  return out;
}

export function fieldsForLine(line: ShopLine, product?: SheetProduct): QuoteFieldDef[] {
  const raw = dedupeFields([...APPLICANT_CORE_FIELDS, ...CO_APPLICANT_FIELDS, ...(CATALOG[line] ?? [])]);
  if (!product) return raw;
  return raw.filter((field) => !field.products || field.products.includes(product));
}

export function emptySheetValues(
  line: ShopLine,
  product?: SheetProduct,
): Record<string, QuoteSheetFieldValue> {
  const values: Record<string, QuoteSheetFieldValue> = {};
  for (const field of fieldsForLine(line, product)) {
    values[field.key] = { value: "", status: "missing", source: "blank" };
  }
  return values;
}

/** New blank master sheet with protection/hazard starters (empty-only defaults). */
export function blankSheetWithDefaults(
  line: ShopLine,
  product?: SheetProduct,
): Record<string, QuoteSheetFieldValue> {
  return applyMasterSheetDefaults(emptySheetValues(line, product)).values;
}

const EXTRACT_ALIASES: Record<string, string> = {
  // Auto vehicle: Original cost new — portals say OCN / cost new
  ocn: "original_cost_new",
  cost_new: "original_cost_new",
  original_cost: "original_cost_new",
  wind_hail_deductible: "wind_hail_deductible",
  wind_deductible: "wind_hail_deductible",
  address: "address",
  swr: "secondary_water",
  garage: "garage_type",
  roof_material: "roof_covering",
  construction_type: "construction",
  living_area: "square_feet",
  square_footage: "square_feet",
  design_wind_speed: "wind_speed",
  date_inspected: "date_inspected",
  four_point_date: "four_point_date",
  exterior_wall: "exterior",
  foundation_type: "foundation",
  current_carrier: "current_carrier",
  mortgagee_address: "mortgagee_address",
  secondary_named_insured: "secondary_named_insured",
  mortgagee: "mortgagee_name",
};

export function extractKeyToSheetKey(line: ShopLine, extractKey: string): string | null {
  const aliased = EXTRACT_ALIASES[extractKey] ?? extractKey;
  const fields = fieldsForLine(line);
  const exact = fields.find((field) => field.key === extractKey || field.key === aliased);
  if (exact) return exact.key;
  const match = fields.find(
    (field) => field.extractKey === extractKey || field.extractKey === aliased,
  );
  return match?.key ?? null;
}

export function groupFields(
  line: ShopLine,
  product?: SheetProduct,
): { group: string; fields: QuoteFieldDef[] }[] {
  const groups: { group: string; fields: QuoteFieldDef[] }[] = [];
  for (const field of fieldsForLine(line, product)) {
    const existing = groups.find((g) => g.group === field.group);
    if (existing) existing.fields.push(field);
    else groups.push({ group: field.group, fields: [field] });
  }
  return groups;
}

export function homeFieldCount(): number {
  return fieldsForLine("home", "homeowners").length;
}
