import { PIPELINE_FIELDS } from "@/lib/wire/pipeline";

export type ColumnDef = {
  key: string;
  label: string;
  defaultOn?: boolean;
};

export const TABLE_COLUMNS: Record<string, ColumnDef[]> = {
  pipeline_fields: PIPELINE_FIELDS.map((field) => ({
    key: field.id,
    label: field.label,
    defaultOn: field.defaultOn,
  })),
  leads: [
    { key: "name", label: "Name", defaultOn: true },
    { key: "firstName", label: "First name", defaultOn: false },
    { key: "middleName", label: "Middle name", defaultOn: false },
    { key: "lastName", label: "Last name", defaultOn: false },
    { key: "dateOfBirth", label: "Date of birth", defaultOn: false },
    { key: "status", label: "Status", defaultOn: true },
    { key: "stage", label: "Deal stage", defaultOn: true },
    { key: "source", label: "Source", defaultOn: true },
    { key: "line", label: "Insurance type desired", defaultOn: true },
    { key: "phone", label: "Phone", defaultOn: true },
    { key: "email", label: "Email", defaultOn: true },
    { key: "mailingAddress", label: "Address", defaultOn: false },
    { key: "city", label: "City", defaultOn: false },
    { key: "state", label: "State", defaultOn: false },
    { key: "zip", label: "ZIP", defaultOn: false },
    { key: "preferredLanguage", label: "Preferred language", defaultOn: false },
    { key: "notes", label: "Notes", defaultOn: false },
    { key: "created", label: "Created", defaultOn: false },
    { key: "action", label: "Shop", defaultOn: true },
  ],
  deals: [
    { key: "title", label: "Deal", defaultOn: true },
    { key: "stage", label: "Stage", defaultOn: true },
    { key: "line", label: "Line", defaultOn: true },
    { key: "subType", label: "Life / Health type", defaultOn: false },
    { key: "state", label: "State", defaultOn: true },
    { key: "city", label: "City", defaultOn: false },
    { key: "zip", label: "ZIP", defaultOn: false },
    { key: "address", label: "Property address", defaultOn: false },
    { key: "shopLines", label: "Shop lines", defaultOn: false },
    { key: "source", label: "Source", defaultOn: true },
    { key: "contact", label: "Contact", defaultOn: true },
    { key: "phone", label: "Phone", defaultOn: true },
    { key: "email", label: "Email", defaultOn: false },
    { key: "assigned", label: "Assigned", defaultOn: true },
    { key: "value", label: "Value", defaultOn: true },
    { key: "premium", label: "Coverage $", defaultOn: false },
    { key: "nextAction", label: "Next", defaultOn: true },
    { key: "updated", label: "Updated", defaultOn: false },
    { key: "esign", label: "E-sign", defaultOn: true },
    { key: "comms", label: "Comms", defaultOn: true },
  ],
  contacts: [
    { key: "name", label: "Name", defaultOn: true },
    { key: "firstName", label: "First name", defaultOn: false },
    { key: "lastName", label: "Last name", defaultOn: false },
    { key: "status", label: "Status", defaultOn: true },
    { key: "source", label: "Source", defaultOn: true },
    { key: "phone", label: "Phone", defaultOn: true },
    { key: "email", label: "Email", defaultOn: true },
    { key: "mailingAddress", label: "Mailing address", defaultOn: false },
    { key: "city", label: "City", defaultOn: true },
    { key: "state", label: "State", defaultOn: false },
    { key: "zip", label: "ZIP", defaultOn: false },
    { key: "dateOfBirth", label: "Date of birth", defaultOn: false },
    { key: "ssn", label: "SSN", defaultOn: false },
    { key: "language", label: "Language", defaultOn: false },
    { key: "maritalStatus", label: "Marital status", defaultOn: false },
    { key: "notes", label: "Notes", defaultOn: false },
    { key: "emailOptOut", label: "Email opt-out", defaultOn: false },
    { key: "smsOptOut", label: "SMS opt-out", defaultOn: false },
    { key: "assigned", label: "Assigned", defaultOn: true },
    { key: "lifetime", label: "Lifetime", defaultOn: true },
    { key: "inForce", label: "In-force", defaultOn: true },
  ],
  accounts: [
    { key: "name", label: "Business", defaultOn: true },
    { key: "status", label: "Status", defaultOn: true },
    { key: "ein", label: "EIN", defaultOn: true },
    { key: "phone", label: "Phone", defaultOn: true },
    { key: "email", label: "Email", defaultOn: false },
    { key: "mailingAddress", label: "Mailing address", defaultOn: false },
    { key: "city", label: "City", defaultOn: true },
    { key: "state", label: "State", defaultOn: false },
    { key: "zip", label: "ZIP", defaultOn: false },
    { key: "employees", label: "Employees", defaultOn: false },
    { key: "lifetime", label: "Lifetime", defaultOn: true },
    { key: "inForce", label: "In-force", defaultOn: true },
  ],
  policies: [
    { key: "number", label: "Policy", defaultOn: true },
    { key: "status", label: "Status", defaultOn: true },
    { key: "insured", label: "Insured", defaultOn: true },
    { key: "line", label: "Line", defaultOn: true },
    { key: "subType", label: "Sub-type", defaultOn: false },
    { key: "carrier", label: "Carrier", defaultOn: true },
    { key: "premium", label: "Premium", defaultOn: true },
    { key: "coverageA", label: "Cov A", defaultOn: false },
    { key: "billingFrequency", label: "Premium frequency", defaultOn: false },
    { key: "premises", label: "Premises", defaultOn: false },
    { key: "premisesCity", label: "Premises city", defaultOn: false },
    { key: "effective", label: "Effective", defaultOn: false },
    { key: "expires", label: "Expires", defaultOn: true },
    { key: "esign", label: "E-sign", defaultOn: true },
    { key: "assigned", label: "Assigned", defaultOn: false },
  ],
  carriers: [
    { key: "name", label: "Carrier", defaultOn: true },
    { key: "naic", label: "NAIC", defaultOn: false },
    { key: "amBest", label: "AM Best", defaultOn: true },
    { key: "territory", label: "Territory", defaultOn: false },
    { key: "agencyCode", label: "Agency code", defaultOn: true },
    { key: "portalLogin", label: "Portal", defaultOn: true },
    { key: "csPhone", label: "Customer service", defaultOn: true },
    { key: "uw", label: "Underwriter", defaultOn: true },
    { key: "uwEmail", label: "UW email", defaultOn: false },
    { key: "uwPhone", label: "UW phone", defaultOn: false },
    { key: "amName", label: "Account manager", defaultOn: false },
    { key: "claimsPhone", label: "Claims phone", defaultOn: false },
    { key: "billingPhone", label: "Billing phone", defaultOn: false },
    { key: "comm", label: "NB / renewal %", defaultOn: true },
    { key: "submission", label: "Preferred submission", defaultOn: false },
    { key: "binding", label: "Binding authority", defaultOn: false },
    { key: "agentPhone", label: "Agent phone", defaultOn: false },
    { key: "website", label: "Website / portal", defaultOn: false },
    { key: "info", label: "Carrier info", defaultOn: false },
    { key: "appetite", label: "Appetite notes", defaultOn: false },
    { key: "lines", label: "Lines", defaultOn: true },
  ],
  tasks: [
    { key: "title", label: "Task", defaultOn: true },
    { key: "due", label: "Due", defaultOn: true },
    { key: "status", label: "Status", defaultOn: true },
    { key: "kind", label: "Kind", defaultOn: true },
    { key: "contact", label: "Contact", defaultOn: false },
    { key: "policy", label: "Policy", defaultOn: false },
    { key: "related", label: "Related", defaultOn: true },
  ],
  quotes: [
    { key: "rank", label: "Rank", defaultOn: true },
    { key: "carrier", label: "Carrier", defaultOn: true },
    { key: "line", label: "Line", defaultOn: true },
    { key: "status", label: "Status", defaultOn: true },
    { key: "premium", label: "Premium", defaultOn: true },
    { key: "quoteNumber", label: "Quote #", defaultOn: true },
    { key: "date", label: "Date", defaultOn: true },
    { key: "links", label: "Links", defaultOn: true },
  ],
  claims: [
    { key: "status", label: "Status", defaultOn: true },
    { key: "carrierClaim", label: "Carrier claim", defaultOn: true },
    { key: "cause", label: "Cause", defaultOn: true },
    { key: "channel", label: "How they told us", defaultOn: false },
    { key: "dateReported", label: "Date reported", defaultOn: false },
    { key: "dateOfLoss", label: "Date of loss", defaultOn: false },
    { key: "description", label: "Short why", defaultOn: false },
    { key: "policy", label: "Policy", defaultOn: true },
    { key: "party", label: "Party", defaultOn: true },
    { key: "producer", label: "Producer ping", defaultOn: false },
  ],
  commissions: [
    { key: "policy", label: "Policy", defaultOn: true },
    { key: "producer", label: "Producer", defaultOn: true },
    { key: "book", label: "Book", defaultOn: true },
    { key: "expected", label: "Expected", defaultOn: true },
    { key: "received", label: "Received", defaultOn: true },
    { key: "variance", label: "Variance", defaultOn: true },
    { key: "status", label: "Status", defaultOn: true },
    { key: "amount", label: "Amount", defaultOn: true },
  ],
  glance: [
    { key: "record", label: "Record", defaultOn: true },
    { key: "kind", label: "Kind", defaultOn: true },
    { key: "status", label: "Status", defaultOn: true },
    { key: "party", label: "Party", defaultOn: true },
    { key: "owner", label: "Assigned", defaultOn: true },
    { key: "when", label: "Date", defaultOn: true },
    { key: "detail", label: "Detail", defaultOn: true },
  ],
  "queue-priority": [
    { key: "due", label: "Due", defaultOn: true },
    { key: "priority", label: "Priority", defaultOn: true },
    { key: "status", label: "Status", defaultOn: true },
    { key: "dollars", label: "$", defaultOn: true },
    { key: "account", label: "Account", defaultOn: true },
  ],
  "queue-attention": [
    { key: "kind", label: "Kind", defaultOn: true },
    { key: "item", label: "Item", defaultOn: true },
    { key: "due", label: "Due date", defaultOn: true },
    { key: "priority", label: "Priority", defaultOn: true },
    { key: "status", label: "Status", defaultOn: true },
    { key: "detail", label: "Detail", defaultOn: true },
  ],
  "queue-open": [
    { key: "number", label: "Policy", defaultOn: true },
    { key: "status", label: "Status", defaultOn: true },
    { key: "party", label: "Party", defaultOn: true },
    { key: "expires", label: "Expires", defaultOn: true },
    { key: "due", label: "Task due", defaultOn: true },
    { key: "priority", label: "Priority", defaultOn: true },
  ],
  "queue-portal": [
    { key: "kind", label: "Kind", defaultOn: true },
    { key: "item", label: "Request", defaultOn: true },
    { key: "policy", label: "Policy", defaultOn: true },
    { key: "status", label: "Status", defaultOn: true },
    { key: "submitted", label: "Submitted", defaultOn: true },
    { key: "detail", label: "Payload", defaultOn: true },
  ],
  pipeline: [
    { key: "title", label: "Deal", defaultOn: true },
    { key: "stage", label: "Stage", defaultOn: true },
    { key: "line", label: "Line", defaultOn: true },
  ],
  merge: [
    { key: "pair", label: "Pair", defaultOn: true },
    { key: "type", label: "Type", defaultOn: true },
    { key: "reason", label: "Why they match", defaultOn: true },
    { key: "action", label: "Review", defaultOn: true },
  ],
  "home-deals": [
    { key: "title", label: "Deal", defaultOn: true },
    { key: "stage", label: "Stage", defaultOn: true },
    { key: "line", label: "Line", defaultOn: true },
  ],
  "decline-log": [
    { key: "date", label: "Date", defaultOn: true },
    { key: "carrier", label: "Carrier", defaultOn: true },
    { key: "deal", label: "Deal", defaultOn: true },
    { key: "result", label: "Result", defaultOn: true },
    { key: "bindable", label: "Bindable", defaultOn: true },
    { key: "premium", label: "Premium", defaultOn: true },
    { key: "covA", label: "Cov A tried", defaultOn: false },
    { key: "why", label: "Why", defaultOn: true },
    { key: "snapshot", label: "Snapshot", defaultOn: false },
  ],
  "eo-gaps": [
    { key: "severity", label: "Severity", defaultOn: true },
    { key: "flag", label: "Flag", defaultOn: true },
    { key: "record", label: "Record", defaultOn: true },
    { key: "detail", label: "Detail", defaultOn: true },
  ],
  "eo-trail": [
    { key: "when", label: "When", defaultOn: true },
    { key: "who", label: "Who", defaultOn: true },
    { key: "what", label: "What", defaultOn: true },
    { key: "record", label: "Record", defaultOn: true },
    { key: "ids", label: "Record ids", defaultOn: true },
    { key: "summary", label: "Summary", defaultOn: true },
  ],
  "fill-learning": [
    { key: "date", label: "Date", defaultOn: true },
    { key: "deal", label: "Deal", defaultOn: true },
    { key: "docType", label: "Doc type", defaultOn: true },
    { key: "field", label: "Field", defaultOn: true },
    { key: "extracted", label: "Extracted", defaultOn: true },
    { key: "corrected", label: "Corrected", defaultOn: true },
    { key: "by", label: "Corrected by", defaultOn: true },
    { key: "carrier", label: "Carrier", defaultOn: false },
    { key: "note", label: "Note", defaultOn: true },
  ],
};

/** New Lead form fields that must appear in the Leads column picker. */
export const LEAD_FORM_COLUMN_KEYS = [
  "firstName",
  "middleName",
  "lastName",
  "dateOfBirth",
  "email",
  "phone",
  "mailingAddress",
  "city",
  "state",
  "zip",
  "line",
  "source",
  "preferredLanguage",
  "notes",
] as const;

export function defaultColumns(tableKey: string): string[] {
  return (TABLE_COLUMNS[tableKey] ?? []).filter((c) => c.defaultOn !== false).map((c) => c.key);
}

export function parseColumns(tableKey: string, raw: string | null | undefined): string[] {
  const allowed = new Set((TABLE_COLUMNS[tableKey] ?? []).map((c) => c.key));
  const picked = (raw ?? "")
    .split(",")
    .map((s) => s.trim())
    .filter((s) => allowed.has(s));
  const next = picked.length ? picked : defaultColumns(tableKey);
  if ((tableKey === "deals" || tableKey === "policies") && !next.includes("esign")) {
    next.push("esign");
  }
  return next;
}
