/** Left-nav rows. One Deals module. One Settings. Stub-only rows (Get Started, Support, Inbox) are gone. */
export const DESK_NAV_ITEMS = [
  { href: "/", label: "Dashboard" },
  { href: "/social", label: "Social" },
  { href: "/leads", label: "Leads" },
  { href: "/deals", label: "Deals" },
  { href: "/contacts", label: "Contacts" },
  { href: "/accounts", label: "Businesses" },
  { href: "/policies", label: "Policies" },
  { href: "/book-health", label: "Book health" },
  { href: "/renewals", label: "Renewals" },
  { href: "/certificates", label: "Certificates" },
  { href: "/suspense", label: "Suspense" },
  { href: "/notices", label: "Notices" },
  { href: "/endorsements", label: "Endorsements" },
  { href: "/service-timeline", label: "Service timeline" },
  { href: "/inspections", label: "Inspections" },
  { href: "/installments", label: "Installments" },
  { href: "/documents", label: "Documents" },
  { href: "/quotes", label: "Quotes" },
  { href: "/merge", label: "Merge" },
  { href: "/work-queue", label: "Work queue" },
  { href: "/claims", label: "Claims log" },
  { href: "/commissions", label: "Commissions" },
  { href: "/scorecards", label: "Scorecards" },
  { href: "/glance", label: "Glance" },
  { href: "/tasks", label: "Tasks" },
  { href: "/automations", label: "Automations" },
  { href: "/calendar", label: "Calendar" },
  { href: "/carriers", label: "Carriers" },
  { href: "/phone", label: "Phone" },
  { href: "/templates", label: "Templates" },
  { href: "/reports", label: "Reports" },
  { href: "/settings", label: "Settings" },
  { href: "/admin", label: "Admin" },
  { href: "/developer", label: "Developer" },
] as const;
